### ISSUE TITLE
Технические требования к размещению на Я.Музыке

### ISSUE THREAD

**Issue by dokxpi** [egoroof/yandex-music-fisher#10]
Требуют, то требуют ..
![1](https://cloud.githubusercontent.com/assets/10334512/5581566/d74fc25e-9064-11e4-866e-e88dcf2c9135.png)
.. вот только качество звучания, как было 192 кбит/с так и оно осталось, возможно это будущее монетизации, но все же, нельзя ли повлиять на этот барьер и "тянуть" mp3 именно в том качестве в котором оно предоставляется на сервис его авторами? 

И конечно, хочу искреннее поблагодарить автора и всех тех, кто принимает участие в развитии yandex-music-fisher Так держать.

**Comment by egoroof** [comment]
К сожалению загружаемые треки проходят обработку и хранятся без любой информации о себе с битрейтом 192 кбит/с. В базе яндекс музыки хранится лишь запись о том, где находится обработанный файл, а также различная информация о файле. Расширение просто обрабатывает эту информацию и сохраняет треки на компьютер. Файлы с другим битрейтом получить неоткуда. Возможно они где-то и хранятся, но нет возможности узнать где.
