### ISSUE TITLE
Возможность скачать понравившиеся треки (те где поставил сердечко)

### ISSUE THREAD

**Issue by LavrovArtem** [egoroof/yandex-music-fisher#100]
Реально очень не хватает и приходится скачивать по одной песне или весь альбом но потом удалять ненужные песни.

**Comment by Gravity89** [comment]
В Яндекс Музыке заходишь в "Моя музыка", там в плейлист "Мне нравится" или в "Понравилось на радио". Скачиваешь плейлист.
