### ISSUE TITLE
Расширение перестало работать в Firefox

### ISSUE THREAD

**Issue by rootk1t** [egoroof/yandex-music-fisher#101]
@egoroof 
В Firefox 52.4.0+, расширение версии 2.1.3 перестало работать.

При заходе на сервисы Яндекс.Музыка и Яндекс.Радио, иконка меняет цвет в зависимости от открытой страницы, но вместо определения имени трека или альбома постоянно появляется табличка:
"Ошибка. Попробуйте позже. Возможно вас заблокировал Яндекс - вам нужно ввести капчу на любой странице Яндекс.Музыки."
Никакой капчи, на страницах яндекса не видно.
Переустановка расширения, не решает проблему.

При этом, в хроме расширение исправно работает, как при входе в аккаунт, так и без него..

![captcha](https://user-images.githubusercontent.com/6153741/31514897-eaa6e36a-af9b-11e7-8641-6bd9d64ac3b6.jpg)

**Comment by egoroof** [comment]
Не могу воспроизвести.

> расширение версии 2.1.3 перестало работать.

**Comment by rootk1t** [comment]
Да все версии работали. Проблем никогда не было.

Самое интересное, что все треки прекрасно проигрываются, и сторонние плагины могут даже скачать .mpeg файлы яндекса, а fisher не видит треки и всё тут. Adblock отключен.

**Comment by egoroof** [comment]
Спасибо, что самостоятельно выявили проблему. Уважаю)

> privacy.trackingprotection.enabled

С этим флагом смог воспроизвести, в консоли вываливается такая ошибка:

> The resource at “https://music.yandex.ru/handlers/album.jsx?album=4734218” was blocked because tracking protection is enabled.

И ссылка на статью https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection

Как можно видеть, запрос идёт на домен Яндекса. Гугл аналитику я удалил ещё в версии 2.1.0. Никакой слежки, аналитики или других левых запросов в расширении нет.

**Comment by egoroof** [comment]
Кстати проверил в стабильной версии (сейчас это 56.0.1) Firefox - с включённым флагом проблема не воспроизводится. Кажется, улучшили алгоритм..

**Comment by rootk1t** [comment]
Кстати, хотел уточнить.

В предстоящем Firefox 57, работа обычные расширения будут заблокированы.

Останутся только WebExtensions. Будет ли yandex-music-fisher работать в 57 версии, или потребуется его полная переработка?

**Comment by egoroof** [comment]
> yandex-music-fisher будет работать в 57 версии

да
