### ISSUE TITLE
Yandex Music API отдельным npm модулем

### ISSUE THREAD

**Issue by flexoid** [egoroof/yandex-music-fisher#104]
Было бы здорово выделить библиотеку для работы с yandex music в виде отдельного npm модуля, с возможностью использовать его из node.js проектов.

Хотелось бы сделать автоматически скрипт для синхронизации плейлистов с локальными файлами, но необходимость реализовывать API отпугивает.

**Comment by egoroof** [comment]
С этим к Яндексу надо обращаться.

По сути апи вот оно https://github.com/egoroof/yandex-music-fisher/blob/master/src/background/yandex.js нужно только добавить парсинг куки, поскольку в браузере это делается автоматически..
