### ISSUE TITLE
После запуска скачивания экстеншн отрубается

### ISSUE THREAD

**Issue by kotchuprik** [egoroof/yandex-music-fisher#11]
Очень любопытная фича для экономии нагрузки :)

**Comment by dokxpi** [comment]
kotchuprik, вы про что?

**Comment by kotchuprik** [comment]
Суть такая, нажал скачать, все скачивается, но экстеншн буд-то выключается, приходится заходить в экстеншны и перезапускать для следующего скачивания.

**Comment by dokxpi** [comment]
**kotchuprik** автора пока нет, но очевидно, вопросы будут таковыми
* что такое *экстеншн* ?
* какой браузер вы используете?
* и конец то концов, сделайте скриншот ошибки

**Comment by kotchuprik** [comment]
1) Yandex Music downloader (Chromium extension)
2) Version 39.0.2171.99 (64-bit)
3) Ошибки нет, вы пользуетесь этим экстеншном?) Без ошибки, пропадает иконка и все.

**Comment by dokxpi** [comment]
О...аналогично  39.0.2171.99 (64-bit)
Да конечно, использую...!
Но в последний раз это было на базе Chrome (32-bit)
![vk](https://cloud.githubusercontent.com/assets/10334512/5806673/0aeb0a14-a024-11e4-8421-1935c61d5f50.png)

**Comment by dokxpi** [comment]
Проверил, иконка пропадает без ошибки 
*Настройки  браузере*..
![test](https://cloud.githubusercontent.com/assets/10334512/5806926/71164b76-a026-11e4-8bd8-28c2a43cba0f.png)

**Comment by egoroof** [comment]
@kotchuprik не уверен, что расширение отрубается. После нажатия на скачивание иконка просто скрывается, чтобы избежать повторных случайных нажатий. А появляется она не везде - только там, где можно скачать (конкретная страница трека, плейлиста, альбома или исполнителя).

Попробуйте так и напишите результаты:
Зайдите сюда: http://music.yandex.ru/album/2209064/track/17902234, скачайте. После начала скачивания иконка исчезнет. Далее выберите другой трек нажатием на название трека. Причём URL должен смениться на соответствующий другому треку. Иконка снова должна появиться. Попробуйте скачать другой трек.

Думаю всё дело в URL, который не при всех действиях на сервисе Яндекс.Музыка сменяется. А расширение определяет, что скачивать именно по URL.

**Comment by kotchuprik** [comment]
Да, так и есть. Но видимо мне везло до этого и она обратно не появлялась после входа на другую страницу.
