### ISSUE TITLE
Не работает загрузка плейлиста

### ISSUE THREAD

**Issue by iCubeDm** [egoroof/yandex-music-fisher#12]
С недавних пор перестала работать загрузка плейлиста. Появляется окошко загрузчика, и через секунд 5-10 пропадает.

**Comment by egoroof** [comment]
Скиньте ссылку на плейлист, пожалуйста

**Comment by iCubeDm** [comment]
Например:
https://music.yandex.ru/users/iCubeDm/playlists/1027

Яндекс.Браузер
Версия
14.12.2125.9577 (2ec243d)
OS X (Yosemite)

**Comment by egoroof** [comment]
Подтверждаю. Буду разбираться. Плейлист, пожалуйста, пока не изменяйте

**Comment by egoroof** [comment]
Проверьте новую версию 0.2.6.1. Проблема ещё наблюдается?

**Comment by iCubeDm** [comment]
Отлично, пошел процесс.

**Comment by egoroof** [comment]
Благодарю за обратную связь :+1:
