### ISSUE TITLE
Нет кнопочки скачивания

### ISSUE THREAD

**Issue by RUnnerTomsk** [egoroof/yandex-music-fisher#17]
Установил, в списке расширений разрешено, показывается.
Кнопки скачивания не появляется. Хром самый свежий (40-й), max os x.

**Comment by RUnnerTomsk** [comment]
Перешел на старую версию Яндекс.Музыки - кнопка появилась.

**Comment by egoroof** [comment]
Сбросьте ссылки страницы, с которой вы пытаетесь скачать (со старой и новой версий Яндекс музыки)

**Comment by RUnnerTomsk** [comment]
В новой версии http://music.yandex.ru/users/тут_мой_ник_в_яндексе/playlists - такая ссылка, при этом уже в альбом ткнуто и он уже играет. Но ссылка не меняется.
В старой версии этот же плейлист: http://music.yandex.ru/#!/users/ei-rec/playlists/2
Кнопка то появится, и тогда я его смог скачать целиком, то не появляется - как сейчас. Поведение пока не понимаю, от чего зависит есть кнопка или нет.

**Comment by egoroof** [comment]
Расширение реагирует на URL - альбом, плейлист, артист или отдельный трек. В новой версии при выборе воспроизведения трека URL не меняется. Нужно нажать на название трека, тогда сменится URL (на нечто подобное: http://music.yandex.ru/users/ei-rec/playlists/3) и появится кнопка.
http://music.yandex.ru/users/ei-rec/playlists - это ссылка на плейлисты пользователя, тут не должно быть иконки. Она появится при переходе на страницу конкретного плейлиста.
http://music.yandex.ru/#!/users/ei-rec/playlists/2 на такие ссылки расширение не должно реагировать, поскольку старая версия Яндекс.Музыки не поддерживается.

**Comment by RUnnerTomsk** [comment]
Вот! Теперь все получилось, спасибо! 
Нужно написать что именно для скачивания плейлиста нужно нажать не просто в иконку плейлиста, а в название плейлиста, когда он справа воспроизводится, тогда открывается именно этот плей-лист и появляется кнопка.
Спасибо за приложение, забыл сказал! Всё-время парился что никак не скачать без танцев с бубнами и поиска треков на других сайтах.
![ei-rec__ _ _ _ _](https://cloud.githubusercontent.com/assets/5242782/6184143/1b34a73a-b380-11e4-8bf3-1e31d333605d.png)

**Comment by gugglegum** [comment]
Я как человек со стороны не совсем понимаю в чем проблема (мало пользуюсь я.музыкой). Что за старая и новая версия я.музыки? Но если проблема всего лишь в парсинге урла, то давайте я напишу подходящее регулярное выражение? Или там всё сложнее?

**Comment by egoroof** [comment]
@gugglegum да там просто расширение смотрит URL и по нему определяет, на какой странице мы сейчас и что следует скачивать. А в новой версии сайта URL меняется только при тыканье на название трека, альбома, плейлиста. Однако если просто нажать там кнопку воспроизведения, то заиграет трек, но URL не изменится.
Наиболее правильное решение - встраивать кнопки скачивания прямо на сайт, напротив каждого трека, альбома и плейлиста. Но это долго, мне не до этого.

**Comment by gugglegum** [comment]
А сейчас доступна только новая версия я.музыки или обе и их как-то можно выбирать?

Вообще, сайт, на котором URL не меняется при переходах внутри сайта — это дурной тон. Вдвойне странно видеть это на сайте Яндекса. Тем более когда в JS есть механизмы управления историей браузера и можно подставить в адресную строку любой (фиктивный) адрес без полной перезагрузки и при этом с корректной навигацией кнопками Вперед/Назад.

Можете написать последовательность действий от главной страницы, чтобы увидеть эту проблему с URL?

**Comment by egoroof** [comment]
Доступны обе версии
Переход из новой в старую:
![toold](https://cloud.githubusercontent.com/assets/2605831/6198840/712c0eb2-b457-11e4-9d88-d2b545db7da2.png)
Переход из старой в новую:
![tonew](https://cloud.githubusercontent.com/assets/2605831/6198843/7c6872ac-b457-11e4-9b53-812faf3eca32.png)

URL меняется, но так, как я выше описал, отчего и бывают непонятки.
![guide](https://cloud.githubusercontent.com/assets/2605831/6198866/fb237c94-b458-11e4-999d-45c831127f16.png)
