### ISSUE TITLE
Недоступна кнопка для скачивания при низком разрешении 1024х600

### ISSUE THREAD

**Issue by Rombo** [egoroof/yandex-music-fisher#18]
На нетбуке низкое разрешение 1024х600, и при выборе группы с большим количеством альбомов для скачивания, список альбомов с чекбоксами выходит за границы экрана. Аналогичная история если окно Chrome уменьшить по высоте. 

как повторить. 
1. открыть YM при низком разрешении, либо свернуть окно Chrome по высоте до 600px
2. найти исполнителя "Queen"
3. нажать иконку приложения (нотку)
4. в выпадающем списке, не возможно проскролить до самого низа, т.к. список выходит за границы экрана (окна)

Chrome v40

PS. отличная программа!

**Comment by egoroof** [comment]
Спасибо за описание проблемы! В ближайшее время разберу варианты решения.

**Comment by gugglegum** [comment]
Думаю надо просто устанавливать высоту всплывающего окна с учётом высоты основного окна.

**Comment by egoroof** [comment]
@gugglegum высота основного окна может меняться в любых пределах. При слишком маленькой высоте получим очень маленькое бесполезное окошко, а на больших экранах (на вертикальных, например) окошко будет очень большим. Думаю достаточно будет пикселей на 100-150 уменьшить высоту и добавить дублирующую кнопку скачивания в самый верх окна. Высота будет оптимальна для маленьких и больших разрешений, а кнопка вверху позволит сразу скачивать дискографию, без ненужных прокручиваний вниз.

**Comment by Rombo** [comment]
@egoroof Надо пробовать... Переместить кнопку наверх весьма остроумно, но окно уменьшать все равно придется под размер экрана. 

Если не уменьшить, то окажется что все равно что-то окажется внизу, недоступно для выбора - не кнопка, так последние строчки списка. А значит окно придется все равно уменьшать. А если так и так окно уменьшать, то может и не трогать кнопку? - она вполне ожидаема к конце списка... (дело привычки - надо пробовать) 

Можно сделать окошко динамичным, по принцпу озвученному @gugglegum, только чтобы не получилось "маленькое бесполезное окошко" или слишком большое - разрешить ему меняться в пределах напр. 300px..1000px.

**Comment by egoroof** [comment]
@Rombo опробуйте новую версию и отпишитесь о результатах

**Comment by Rombo** [comment]
@egoroof проше прощения, не было доступа к нетбуку на прошлой неделе - протестирую в кратчайшее время

**Comment by Rombo** [comment]
@egoroof, да, все отлично - при растягивании на полный экран можно проскролить до кнопки "Сохранить"
Спасибо большое!
Роман
(версия 0.2.6.2)
