### ISSUE TITLE
Неправильно сохраняет треки

### ISSUE THREAD

**Issue by lexuses** [egoroof/yandex-music-fisher#21]
При сохранении любого альбома все треки являются этой песней "Rick Astley - Never gonna give you up". И неважно, какую группу или исполнителя скачивать, на выходе только эта композиция.

Все сохраняются треки с правильным названием.

Google Chrome Версия 42.0.2311.90 m

Yandex Music Fisher 0.2.7
Wed Apr 29 2015 10:57:25 GMT+0300 (RTZ 2 (зима))
Operating system: win
Architecture: x86-32

**Comment by egoroof** [comment]
Вангую, что в настройках расширения в маске названии файлов прописано "Rick Astley - Never gonna give you up". Сбросьте настройки - на странице настроек есть специальная кнопка для этого.

**Comment by lexuses** [comment]
Нет, речь как раз не в названии, а в аудио дорожке. Названия все правильные. Вот скрин настроек:
![qip shot - screen 028](https://cloud.githubusercontent.com/assets/3509773/7409751/ca97b1bc-ef31-11e4-9570-a52eb52620d4.png)

**Comment by egoroof** [comment]
Оу, это интересно, дайте любую ссылку, откуда качаете

**Comment by lexuses** [comment]
Например, вот этот альбом: https://music.yandex.ru/album/2191271. Но я пробовал разные альбомы. Пробовал из под инкогнито и на другом компе - результат все тот же трек.

**Comment by egoroof** [comment]
О ужас, это подтвердилось, нас развёл яндекс. буду изучать

**Comment by gugglegum** [comment]
Похоже, что Яндекс как-то научился различать когда музыка скачивается веб-плеером, а когда вашим плагином.

**Comment by egoroof** [comment]
@gugglegum не, там они постоянно у себя апи меняют, вот и сейчас

**Comment by egoroof** [comment]
В 0.2.7.1 всё должно чётко работать

**Comment by lexuses** [comment]
Все работает! Спасибо большое за Ваш плагин!

**Comment by kozlosoft** [comment]
а в яндексе веселые парни сидят. того гляди в апи карт анонс hl 3 произойдет

**Comment by egoroof** [comment]
@kozlosoft ахаха :smile:
