### ISSUE TITLE
перестал работать Yandex Music Fisher

### ISSUE THREAD

**Issue by Dmitro4ekalov** [egoroof/yandex-music-fisher#22]
Здравствуйте! Пользуюсь давно Вашим расширением, всё было отлично, а сейчас расширение у меня перестало работать: не появляются иконки, на которые нужно нажимать чтобы скачать музыку. Пробывал разные альбомы, плейлисты. Скачал заново и переустановил Ваше расширение - не помогло.
Версия расширения 0.2.7.1
Скачивал всегда Yandex браузером Версия 15.4.2272.3716
Пробывал другим браузером (Амиго), который тоже не дал результата. Версия 32.0.1725.111 (12a8da)
Расширение отличное, Респект Вам и Уважение!
Пожалуйста помогите с описанной проблемой

**Comment by egoroof** [comment]
Здравствуйте!

Только что установил Яндекс.Браузер (версия 15.6.2311.3927). Проверил - у меня работает.
Что я ещё обнаружил, так это то, что расширение выключается браузером, поэтому перед скачиванием его необходимо включить (на странице расширений). На снимках экрана выделил красным:
![1](https://cloud.githubusercontent.com/assets/2605831/8147526/3900ad74-12a1-11e5-9c03-12d60001c09e.png)
![2](https://cloud.githubusercontent.com/assets/2605831/8147527/3d134c46-12a1-11e5-89d0-46482ff36004.png)
Проверьте, выключено ли у вас расширение и отпишитесь о результатах.

**Comment by Dmitro4ekalov** [comment]
установил только что тоже Яндекс.Браузер (версия 15.6.2311.3927)
всё включал, и при запуске браузера и потом в расширениях смотрел всё включено, а иконки всё равно не появляются

**Comment by egoroof** [comment]
А скиньте адрес страницы (URL), находясь на которой, вы ожидаете увидеть иконку для скачивания.

**Comment by Dmitro4ekalov** [comment]
https://music.yandex.ua/album/2775807

**Comment by egoroof** [comment]
Спасибо, ваша проблема подтвердилась, в ближайшее время буду изучать причину.

**Comment by Dmitro4ekalov** [comment]
Спасибо, отпишитесь пожалуйста, как решите проблему

**Comment by egoroof** [comment]
Причину выяснил. Скоро обновлю расширение, однако пока вы можете скачивать, изменив в адресной строке домен с yandex.ua на yandex.ru. Например, предыдущая ссылка будет такая: https://music.yandex.ru/album/2775807

**Comment by Dmitro4ekalov** [comment]
вбиваю https://music.yandex.ru/album/2775807  а браузер всё равно открывает https://music.yandex.ua/album/2775807
может потому что я с Украины (ip)

**Comment by egoroof** [comment]
Да, скорее всего именно так. Ждите обновление, я напишу, как обновлю расширение

**Comment by Dmitro4ekalov** [comment]
Спасибо огромное, удачи Вам

**Comment by egoroof** [comment]
Обновил расширение - [скачать можно тут](https://github.com/egoroof/yandex-music-fisher/archive/master.zip).
Пожалуйста, отпишитесь, работает ли скачивание музыки у вас.

**Comment by Dmitro4ekalov** [comment]
расширение переустановил, иконки теперь появились, но при нажатии на них - скачивание музыки не начинается
Яндекс.Браузер (версия 15.6.2311.3927)

**Comment by egoroof** [comment]
Спасибо, ждите следующее обновление

**Comment by Dmitro4ekalov** [comment]
жду с не терпением

**Comment by egoroof** [comment]
[Обновил](https://github.com/egoroof/yandex-music-fisher/archive/master.zip)
Пожалуйста, проверьте скачиваются ли треки, обложки альбомов и показывается ли картинка в оповещении (которое появляется при начале загрузки).

**Comment by Dmitro4ekalov** [comment]
ок, щас проверю

**Comment by Dmitro4ekalov** [comment]
Всё отлично работает!
треки и обложка скачиваются, и картинка в окошке оповещения загрузки показывается
спасибо Вам огромное

**Comment by egoroof** [comment]
Всегда пожалуйста)
Вам спасибо за оповещение о проблеме!
