### ISSUE TITLE
1.0.2 отсутствует манифест. Google Chrome

### ISSUE THREAD

**Issue by bugsmafia** [egoroof/yandex-music-fisher#23]
Ошибка при попытке установить расширение.
Отсутствует манифест.

**Comment by egoroof** [comment]
А распаковывали в текущую папку или нет? Нужно в текущую, проверьте.
Можете ещё зайти в папку yandex-music-fisher, там должен быть файл manifest.json и различные папки.

**Comment by egoroof** [comment]
Как попробуете, отпишитесь о результатах

**Comment by 4ndv** [comment]
Была та же проблема на 1.1.0, расширение установилось перетаскиванием папки src

**Comment by egoroof** [comment]
Значит вы качаете исходный код, а нужно скачивать дистрибутив в виде архива, где указан номер версии. На странице описания ссылка дана на него.
![2015-07-08 15 54 43](https://cloud.githubusercontent.com/assets/2605831/8565632/de2d1b2a-2589-11e5-860b-1c01da5be513.png)

**Comment by bugsmafia** [comment]
Проблема исчерпана.
Была использована не src папка, а корневая
