### ISSUE TITLE
Проблема психологического характера

### ISSUE THREAD

**Issue by prostjololo** [egoroof/yandex-music-fisher#26]
какой шанс того что после использования расширения тебя найдут и отправят в места не столько отдаленные?

**Comment by egoroof** [comment]
Я не юрист, но, думаю, нулевой - максимум штраф платить придётся. Разработчику. Ну т.е. мне :fearful: 
Написал в поддержку Яндекса. Как ответят - напишу тут.

**Comment by prostjololo** [comment]
а как же вычисление по ip того кто качал или это не отслеживается?

**Comment by prostjololo** [comment]
или тут работает принцип того что всем неважно, что там люди делают, ни провайдер не сдаст и сам сервис зомарачиваться не будет

**Comment by egoroof** [comment]
Отслеживается IP, верно.
Если захотят, вас легко найдут и назначат пожизненное заключение в тюрьме строгого режима.. :facepunch: 
Только, сначала нужно определиться с нарушениями.

А вы знаете, что расширение выполняет аналогичные действия, как браузер во время прослушивания музыки на сайте? Когда вы запускаете там музыку, браузер получает информацию о треке. Музыка воспроизводится на вашем компьютере, т.е. браузер скачивает трек, прежде чем его проиграть.
В чём разница, спросите вы? В том, что браузер хранит трек где-то у себя в лесу в одичалом виде (называется "кэш браузера"). А расширение собирает треки по папочкам с понятными названиями. Вот и вся разница.

Вот гляньте пункт 1.6 отсюда: https://legal.yandex.ru/music_termsofuse/ - "Сервис предлагает Пользователю возможность бесплатного поиска и **прослушивания музыкальных композиций (фонограмм)** при помощи своего персонального компьютера." В рамках этого пункта вы и прослушиваете скачанные треки.
Пункт 2.3 "Все Материалы и Плеер предназначены исключительно для личного некоммерческого использования в рамках технических возможностей, предоставляемых Сервисом"
- пользуемся лично - да,
- деньги на этом не зарабатываем - да,
- технические возможности, предоставляемые Сервисом позволяют скачивать треки и получать информацию о них

Вы всё ещё беспокоитесь? Тогда мы идём к вам..
![284522_600 1](https://cloud.githubusercontent.com/assets/2605831/9109979/7fa4e8c2-3c6c-11e5-83b7-503ce3cabcf6.jpg)

**Comment by prostjololo** [comment]
Я так понимаю тут вы меня подкололи, если даже вычислят, то штраф пропишут, ущерб же не более 100 тысяч рублей, это явно

"Отслеживается IP, верно.
Если захотят, вас легко найдут и назначат пожизненное заключение в тюрьме строгого режима.. "

А то что вы описали про браузер, это да, он же скачивает треки в кэш, в любом случае, просто я так понимаю их не так легко вытащить оттуда.

А вообще стоит беспокоиться если человек сидел под своим IP и аккаунтом яндекс музыки и пользовался расширением на свои же плейлисты?

**Comment by prostjololo** [comment]
То есть фактически, используя расширение, сервис считает что человек просто прослушивает музыку? просто очень быстро? а то что они идут на компьютер в виде mp3 файлов, сервис это уже не видит и люди которые там сидят тоже.

**Comment by agorshkov23** [comment]
Сервер сам отдает их как mp3-файл))
@prostjololo, блин, не загоняйся :) всё нормально :)

**Comment by egoroof** [comment]
> А вообще стоит беспокоиться если человек сидел под своим IP и аккаунтом яндекс музыки и пользовался расширением на свои же плейлисты?

Теоретически, согласно пункту 2.6 могут заблокировать вашу учётную запись (если решат, что вы что-то нарушаете).

> То есть фактически, используя расширение, сервис считает что человек просто прослушивает музыку? просто очень быстро?

Не совсем, там всё-же можно отследить, что запросы идут не с сайта.

> а то что они идут на компьютер в виде mp3 файлов, сервис это уже не видит и люди которые там сидят тоже.

Верно.

**Comment by prostjololo** [comment]
Главное что бы повестку в суд не намутили

**Comment by iCubeDm** [comment]
Ну, насколько я понимаю, то в России закон - это вещь весьма абстрактная и действующая точечно. Если многоуважаемый автор чем-то "насолит" компании Яндекс, или каким-то образом перейдет дорогу кому-нибудь из тамошних власть имущих, то тогда да, его могут прижать, причем очень легко и свободно, и не только из-за этого приложения. (Каждый из нас хоть какую-то но пиратскую софтину/музыку/что угодно хранит на компе). Но даже в этом случае, вряд ли такая компания, как Яндекс будет третировать автора. Вангую "худший" вариант развития событий - они посмотрят код расширения, попросят закрыть реп и позовут на работу в Я.Музыку на фронтенд ;)

**Comment by horosgrisa** [comment]
@iCubeDm Если я не ошибаюсь, компания Yandex даже не является российской, так как зарегистрирована в Голландии. Но на всякий случай лучше постоянно делать бэкапы этого репозитария на локальный компьютер.

**Comment by prostjololo** [comment]
Насколько я понимаю никто не скрывает свой IP, потому что такая компания не будет искать тысячи обычных людей, тем более доказать вину сложно будет, плюс мы живем в России и могут отправить в суд только если кто то точит "зуб" на конкретного человека

**Comment by gugglegum** [comment]
@horosgrisa бэкап в любом случае есть у разработчика. Это же git — у него децентрализованное хранилище. Каждый, кто выгрузил к себе репозитарий, выгрузил его себе целиком, вместе со всей историей коммитов.

**Comment by horosgrisa** [comment]
@gugglegum Я чуть неправильно выразился. Имелось в виду не держать исходники только на Github-е.

**Comment by gugglegum** [comment]
@horosgrisa, ну так они и так как минимум у автора в его локальном репозитарии. Причём потенциально даже более свежие. Или вы заботитесь не о сохранении кода, а о его доступности для конечных пользователей? Ну, если так, то есть конечно и другие хостинги, но на них имеет смысл выкладывать только если заблокируют на гитхабе. Но это очень маловероятно вообще.

**Comment by egoroof** [comment]
Ответили из поддержки:

> Спасибо за письмо! 
> Использование такого загрузчика нарушает условия использования сервиса.
> 
> Легальная возможность сохранять музыку есть в нашем мобильном приложении: https://music.yandex.ru/apps

Уточню у них, какие конкретно пункты соглашения нарушаем.

**Comment by prostjololo** [comment]
Если бы это приложение сохраняло по человечески, а не просто в кэш свой, из которого не вытащишь музыку. Сделали подписку, а до ума не довели

**Comment by iCubeDm** [comment]
Если бы оно сохраняло по человечески, то треки можно было бы вытащить, и использовать их в сторонних приложениях когда угодно (читай после окончания подписки). Поэтому, скорее всего, приложение каким-то образом кодирует файлы, чтобы их невозможно было использовать извне приложения... Всё-таки всегда на первом месте заработок денег.

**Comment by prostjololo** [comment]
Лучше бы сделали как у гугл музыки, без подписки ничего не сделаешь даже на ПК. Я ничего не имею против подписок, но такое кэширование меня вообще не устраивает

**Comment by prostjololo** [comment]
А если привязан номер к яндексу, стоит удалить, или это неважно?

**Comment by egoroof** [comment]
> это неважно

**Comment by prostjololo** [comment]
Что там слышно от тех поддержки?

**Comment by egoroof** [comment]
Ничего не слышно. А всё потому, что ничего не нарушаем.
Про авторские права на треки - [Свободное использование произведений](https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D0%BE%D0%B5_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B9)
На условия использования Яндекс.Музыки [уже приводил ссылку](https://legal.yandex.ru/music_termsofuse/), и разбирал по пунктам, что использование расширения не противоречит условиям.

**Comment by prostjololo** [comment]
Замечательно, значит можно забирать песни пока дырку не закрыли

**Comment by egoroof** [comment]
хех http://geektimes.ru/post/261198/

**Comment by gugglegum** [comment]
Мда. Градус безумия в Интернете и мире увеличивается с каждым годом. Ещё недавно считалось, что ссылка на пиратский варез не считается нарушением, т.к. это всего лишь ссылка, а нарушителем является раздающий сервер. Сейчас уже за это во всю блокируют сайты. И ладно бы этот бред был только в России, это бы я ещё понял, но этот бред распространяется по всему миру. Здесь и этот идиотский DMCA, и "право на забвение", которое зародилось в Европе, но было лихо подхвачено нашим "взбесившимся принтером". Попытки на законодательном уровне контролировать распространение информации противоречат сути интернета. Интернет саморегулирующийся организм. Информация в нём всё равно будет передаваться до тех пор пока есть те, кто в этом заинтересован. На мой взгляд уже давно настал момент, когда пора массово, всем миром уходить в подполье, в Tor...

**Comment by horosgrisa** [comment]
@gugglegum Не могу с вами не согласиться. То что происходит с интернетом в последнее время ужасно, и не только в России. Но я больше склоняюсь к идее I2P, и обмену информации между людьми. И вообще, независимости от каких либо серверов.
