### ISSUE TITLE
Пункт скачивания лучших треков испонителя

### ISSUE THREAD

**Issue by nikolaev-vl** [egoroof/yandex-music-fisher#27]
Привет, огромное спасибо за экстеншн! 

Было бы очень круто добавить возможность скачивания 10ти первых самых популярных треков испонителя. Еще раз хочу поблагодарить за потраченное время и силы.

**Comment by egoroof** [comment]
Привет!

Спасибо за отзыв! :)

>возможность скачивания 10ти первых самых популярных треков испонителя

Добавил себе в todo.

**Comment by uglide** [comment]
:+1:

**Comment by TheTitanrain** [comment]
Плюсанул бы, если бы можно было голосовать за новую функциональность.

**Comment by egoroof** [comment]
Будет в следующей версии
