### ISSUE TITLE
Дополнение удаляется после перезагрузки Яндекс.Браузера

### ISSUE THREAD

**Issue by TheTitanrain** [egoroof/yandex-music-fisher#29]
Устанавливаю обновление перетаскиванием на вкладку дополнений. Она появляется в списке дополнений и корректно работает.
![2015-09-25 18-28-49 2](https://cloud.githubusercontent.com/assets/1952721/10096275/7e4e850a-63b3-11e5-81b3-f819aecabcce.png)
После закрытия и открытия Я.Бро дополнения нет в списке дополнений.
![2015-09-25 18-28-32](https://cloud.githubusercontent.com/assets/1952721/10096278/87e9ebea-63b3-11e5-920a-1460108142b2.png)

**Comment by egoroof** [comment]
Я обнаружил только одну причину, когда так происходит (возможно есть и другие): если переместить или переименовать папку с расширением, то при запуске Яндекс Браузера расширения не будет в списке. Попробуйте снова добавить расширение в список, затем закрыть и открыть браузер. По-прежнему расширение пропадает?

**Comment by TheTitanrain** [comment]
Добавляю, папку не трогаю. Закрываю, открываю - пропадает.
Переместил в папку с Я.Браузером, тоже самое.

**Comment by egoroof** [comment]
А какая операционная система и версия браузера?

**Comment by TheTitanrain** [comment]
Win 10 Pro
Я.Браузер 15.9.2403.2966

**Comment by egoroof** [comment]
В windows 10 подтвердилось такое поведение, хотя в 8.1 проблем нет.
Написал в поддержку Яндекс.Браузера.

**Comment by TheTitanrain** [comment]
Совсем забыл сказать, что такое на двух разных компах с Win10.

**Comment by egoroof** [comment]
Ответили из поддержки Яндекс.Браузера:
> Благодарю за сообщение. Мы проверим указанную Вами информацию. Если есть ошибки на нашей стороне, они будут исправлены в следующих версиях программы. Ваше письмо передано разработчикам.

**Comment by TheTitanrain** [comment]
ОК

**Comment by silentbay** [comment]
Подобная ситуация и с другими дополнениями установленным в Chromium. Проблема решилась упаковкой дополнения в CRX и установка уже оного.

**Comment by TheTitanrain** [comment]
Так как поставить дополнение, чтобы не удалялось?

**Comment by dokxpi** [comment]
Наблюдаю аналогичное падение (Windows 7): если закрыть Яндекс.Браузер то при запуске расширения не будет в списке. Версия 15.10.2454.2437 beta. Следовательно можно не сомневаться в том, что напортачил именно Яндекс
***
# Я люблю тебя, Яндекс
**TheTitanrain**, специально для вас упаковал расширение ```Yandex Music Fisher (1.3.1)``` в crx файл, [скачайте его и установите как обычное расширение](https://github.com/dokxpi/yandex-music-fisher/blob/master/CRXPackage/src.crx?raw=true):
1. Откройте страницу расширений ```browser://tune```
2. Перенесите туда мышью src.crx файл, после чего в браузере появится новое расширение 
Всё. Теперь расширение больше не будет исчезать

PS.1. На всякий случай, оставлю это здесь [(src.pem)] (https://raw.githubusercontent.com/dokxpi/yandex-music-fisher/master/CRXPackage/src.pem), но он (файл кючей) вам не нужен
PS.2. На заметку. Яндекс.Браузер — это просто урезанный Google Chrome

**Comment by TheTitanrain** [comment]
Спасибо!

PS Точнее это другая ветка Chromium

**Comment by dokxpi** [comment]
```Yandex Music Fisher (1.4.0)```
[CRX-файл](https://github.com/dokxpi/yandex-music-fisher/blob/master/CRX/v1.4.0/src.crx?raw=true)

**Comment by TheTitanrain** [comment]
спс

**Comment by silentbay** [comment]
Объясняю ситуацию. Качаем и распаковываем архив (пример всё в папке "загрузки"), переносим папку с расширением в браузер и устанавливаем. Браузер не копирует файлы в свой профиль и расширение работает из папки "загрузки". А мы такие умные думаем:"установили же, можно и удалить, что накачали". При следующем запуске браузера - расширения нету.

**Comment by TheTitanrain** [comment]
Насколько помню, не удалял и все равно расширение исчезало.

**Comment by dokxpi** [comment]
silentbay, удалять нечего не нужно
TheTitanrain, ваша проблема решена и она не имеет общего с проблемой silentbay

**Comment by Gravity89** [comment]
@dokxpi, назвался груздем - полезай в короб. Нужна версия CRX под 1.5.0 или инструкция как их самому клепать =)

**Comment by egoroof** [comment]
@Gravity89 
![xc09flts7w](https://cloud.githubusercontent.com/assets/2605831/12013477/5451e038-ad52-11e5-9b1e-2c818cc26fc8.gif)

**Comment by TheTitanrain** [comment]
Спасибо! Очень наглядно.

**Comment by Gravity89** [comment]
Спасибо!

**Comment by dokxpi** [comment]
```Yandex Music Fisher (1.5.0)``` 
Dec 26, 2015 - [CRX-файл](https://github.com/dokxpi/yandex-music-fisher/blob/master/crx/v1.5.0/src.crx?raw=true)

**Comment by egoroof** [comment]
Сегодня пришло письмо из поддержки яндекса:

>Здравствуйте!
>
>Прошу прощения за задержку с ответом.
>
>Пожалуйста, проверьте, возникает ли такая ситуация в последней версии браузера. 
>
>Загрузить её можно нажав на кнопку с меню браузера>>Дополнительно>>О браузере Yandex.
>
>Мы внесли правки, которые были направлены на решение похожей проблемы.
>
>Сообщите нам, решена ли она после обновления.

Я проверил, проблема не решена, ответил им.

До этого ещё пару раз такое присылали (как-будто робот слал):

> Здравствуйте!
> 
> Прошу прощения за задержку с ответом.
> 
> Мы продолжаем вести работу над задачей, созданной по Вашему обращению. Для ее завершения понадобится еще некоторое время. Мы будем продолжать держать Вас в курсе, спасибо за терпение!

**Comment by TheTitanrain** [comment]
Тех поддержка яндекса вообще какая-то не очень. У меня проблема с яндекс.диском была - похожие по содержанию письма слали на протяжении месяцев трех. Ждем, когда-нибудь починят...

**Comment by dokxpi** [comment]
TheTitanrain, обязательно внукам в __todo__ добавить, иначе не сбудется xD

**Comment by egoroof** [comment]
Теперь можно установить из [интернет-магазина Chrome](https://chrome.google.com/webstore/detail/yandex-music-fisher/gkdpmbjlfgjbnleinnojgpgoljaokbni), тогда не будет удаляться.
