### ISSUE TITLE
доступен битрейт 320 КБит/с

### ISSUE THREAD

**Issue by egoroof** [egoroof/yandex-music-fisher#30]
Ура, товарищи, сервис яндекс.музыка обновился.
Теперь доступны треки с качеством 320 КБит/с.
Сейчас скачивание через расширение работает по старой схеме (192КБит/с).
Ждите обновление :)

**Comment by egoroof** [comment]
Добавлено в https://github.com/egoroof/yandex-music-fisher/commit/e906337558c77fca1efaf3b9cbdf405a82e96995.
Будет доступно со следующей версии расширения.

**Comment by sevenreasons** [comment]
В каких случаях доступен 320? Не совсем понятно, один альбом скачался в 320, кроме двух треков.

**Comment by egoroof** [comment]
Это не расширение выбирает, какое качество качать, а сам сервис Яндекс.Музыка отдаёт треки с наилучшем качеством. Если у них есть трек в 320 - они его дают, его нет, то в 192 (или в другом).

**Comment by dokxpi** [comment]
Я вас люблю, - супер..!!

**Comment by egoroof** [comment]
@dokxpi :smile:

**Comment by DeltaKilo** [comment]
А есть возможность зафорсить 192кбит/с? Для меня 320 избыточен, а места жалко. :(

**Comment by egoroof** [comment]
@DeltaKilo да, добавил настройку - будет доступно в следующей версии.
Но, это будет работать, пока яндекс не уберёт такую возможность.
