### ISSUE TITLE
неправильный размер загрузок и процент завершения

### ISSUE THREAD

**Issue by dokxpi** [egoroof/yandex-music-fisher#31]
![2015-10-26 05-15-43](https://cloud.githubusercontent.com/assets/10334512/10720903/a196dfea-7ba4-11e5-9c28-c9f8ef08bbdd.png)

**Comment by dokxpi** [comment]
![2015-10-26 05-15-43](https://cloud.githubusercontent.com/assets/10334512/10720920/daf2f9d6-7ba4-11e5-98bd-58609e0921ec.png)

**Comment by egoroof** [comment]
Вот тут это описано: https://github.com/egoroof/yandex-music-fisher/releases/tag/v1.3.0

**Comment by tarelka95** [comment]
Имеем мы:
Яндекс.Музыка отсылает инфу о старом размере файла (качества 192Кбит/с), поэтому если скачивается трек качества >192Кбит/с, то информация в загрузчике будет с неверным общим размером и его процентным соотношением.

У меня появилась идея, как сделать псевдоисправление:
у нас есть например плейлист на 500 мб(согласно инфе яндекса "192Кбит/с" качества), а по факту после скачивания 800мб.
Допустим первый файл качества "320Кбит/с" (в плейлисте), "fisher" его качает (пока все так же 500 мб).
Далее считываем размер файла которого скачали (вы же выводите размер того, сколько уже скачалось), и пересчитываем общий размер (записываем временно инфу о новом размере, и складываем новую инфу + старую, исключая тот размер, о котором есть новая инфа).
Если дальше так же продолжать, то у нас получится в конце скачивания, валидный итоговый размер и валидные проценты ( 100% ).
Но в процессе будет выглядеть, так что итоговый размер у нас постоянно увеличивается.(поэтому, псевдоисправление).

**Comment by egoroof** [comment]
@tarelka95 а есть вариант по-лучше: брать размер файлов не у API яндекса, а смотреть у самих файлов. Для этого предварительно нужно опросить все файлы HEAD запросами. Когда-нибудь, наверно, запилю такое.

**Comment by egoroof** [comment]
Теперь размер загрузок будет отображаться в виде диапазона: A - B, где A - размер, при котором все треки с битрейтом 192 кбит/с, B - размер, при котором все треки с битрейтом 320 кбит/с. Поскольку в альбомах и плейлистах треки могут быть с различным битрейтом (от 192 до 320), то общий размер треков не выйдет за этот диапазон.

**Comment by denchuk-killer** [comment]
Я таки не понял, качать в 320 кбпс можно или нет? У меня даже с авторизацией качает только 192 кбпс

**Comment by egoroof** [comment]
@denchuk-killer можно, но для этого необходимо купить подписку на яндекс.музыке, тогда автоматически будет качать в 320 kbps
