### ISSUE TITLE
папка сохранения

### ISSUE THREAD

**Issue by 4kin** [egoroof/yandex-music-fisher#33]
добавить папку сохранения
например в настройках  для продвинутых позователей

**Comment by 4kin** [comment]
браузер chrome

**Comment by mrtwister** [comment]
Присоединяюсь. Было бы здорово, если реализовывается. Когда в настройка стоит галка "Всегда указывать папку для сохранения" висит 8 вопросов куда сохранять. Просто сидишь и тыкаешь кнопку "сохранить" все время.

**Comment by egoroof** [comment]
Расширения могут сохранять загрузки только в папку, указанную в настройках браузера. В этой папке могут быть созданы подпапки. Но расширение не может сохранять в произвольную папку.

@mrtwister а почему бы не снять эту галочку? Хотя бы на время скачивания, ибо расширение не может переопределить эту настройку браузера.

**Comment by mrtwister** [comment]
@egoroof я так и делаю. Я подумал, может есть какой то еще способ, сохранять файлы.

**Comment by mikeshiyan** [comment]
P.S.: Если скачиваете всегда один и тот же плейлист, то можно создать символьную ссылку. Т.о. файлы будут сразу падать в нужное место. Напр., как я сделал:
> `C:\Users\Mike>mklink /J "Downloads\Мне нравится" "YandexDisk\Music\ya.music"`

**Comment by egoroof** [comment]
Вероятно, создание произвольной подпапки будет реализовано: https://github.com/egoroof/yandex-music-fisher/issues/60 (возможно не совсем то, что вы хотели)
