### ISSUE TITLE
название плейлистов

### ISSUE THREAD

**Issue by 4kin** [egoroof/yandex-music-fisher#34]
При запущенной скачки альбомов происходит сброс названия плейлиста
те при попытке создать плейлист убирается окно (где вводить название плейлиста) сразу как только добавляется новая песня из очереди Вашего замечательного плагина

**Comment by 4kin** [comment]
браузер chrome

**Comment by 4kin** [comment]
везде делается рефреш и все вплывающие окна убираются

**Comment by egoroof** [comment]
Объясните по-подробнее, о чём речь - у расширения нигде нет ввода названия плейлиста. Покажите снимок экрана.

**Comment by dokxpi** [comment]
4kin, не надо нечего "вводить", названия альбомов берется с Яндекс.Музыки
https://github.com/egoroof/yandex-music-fisher#Пути-сохранения
