### ISSUE TITLE
закрытие браузера

### ISSUE THREAD

**Issue by 4kin** [egoroof/yandex-music-fisher#35]
браузер chrome во время скачки нажал закрыть браузер (крестик на окне).
плагин не заругался и все закрылось
при повторном запуске браузера chrome очередь осталась пустой

**Comment by egoroof** [comment]
Возможность скачивать в фоновом режиме (даже при закрытии браузра) будет в следующей версии. По-умолчанию этот режим отключён, включается в настройках.
