### ISSUE TITLE
Странное поведение при подсчитывании размера и процента завершения

### ISSUE THREAD

**Issue by mrtwister** [egoroof/yandex-music-fisher#36]
Привет. Где то ошибка при подсчете прогресса плейлиста. Браузер Chrome.
![image](https://cloud.githubusercontent.com/assets/379527/10988204/1a660c68-8486-11e5-8fb5-d2825c99a71d.png)

**Comment by egoroof** [comment]
Спасибо, что сообщили о проблеме!
Однако она уже описана здесь: https://github.com/egoroof/yandex-music-fisher/issues/31
