### ISSUE TITLE
Переименование дубликатов файлов ..1 -> 2 -> 3

### ISSUE THREAD

**Issue by dokxpi** [egoroof/yandex-music-fisher#37]
yandex-music-fisher автоматически переименовывает файлы в результирующей папке, если такой уже существует (добавляет циферку 1 -> 2 -> 3 и т.д. в скобках), для чего, почему бы просто не перезаписать?  Это значительно упростило бы задачу с зеркалированием каталогов, да собственно зачем городить дубликаты .. 
Источник зарождение вопроса: http://www.cyberforum.ru/post4299447.html

**Comment by egoroof** [comment]
Были случаи, когда названия треков настолько длинные, что они сокращаются до 50 символов. Так вот иногда бывает 50 символов совпадают у нескольких треков, поэтому такой способ позволяет сохранить все треки.
Но я думаю сделать проверку на совпадение имён и, в таком случае, принудительно нумеровать треки. Тогда смогу решить описанную здесь задачу.

**Comment by dokxpi** [comment]
А если чуточку упростить 
1. Перезаписывать все треки 
2. Сделать проверку для треков в которых в названии  > 45 символов 

Во всяком случаи ждем любой реализации, спасибо вам

**Comment by egoroof** [comment]
Будет доступно в следующей версии

**Comment by dokxpi** [comment]
Спасибо,
теперь всё так, как должно быть
* * *
Ps. Настройки.
 Возможно кому-то пригодится
```
:: Зеркалирование файловых ресурсов утилитой robocopy (11.08.2009)
:: http://zheleznov.info/backup_mirror.htm

:: Файл настроек задания программы Robocopy
:: Задание: создать зеркало директории E:\Musiccorp\MUSICSD :в каталог J: на переносном жестком диске

:: Копируемый каталог
/SD:E:\Musiccorp\MUSICSD

:: Копия будет храниться на переносном жестком диске, буква диска может меняться
:: Каталог назначения, указан относительный путь
.\MUSIC\MUSICSD

:: Перечень каталогов, которые НЕ надо копировать
:: Внимание! Исключенные из копирования подкаталоги не удаляются
:: из каталога назначения, если они уже там есть
/XD
E:\Musiccorp\MUSICSD\#temp

:: Запись в файл журнала
/LOG:MIRror.log
/TEE	:: также выводить сообщения в консоль
/NP	:: не показывать прогресс (%) для каждого файла

:: Опции копирования
/MIR	:: Создать зеркало (MIRror)

:: Повтор копирования в случае ошибок
/R:10	:: количество повторов
/W:30	:: время ожидания перед повтором в секундах
```
