### ISSUE TITLE
Feature: Возможность изменения места загрузки

### ISSUE THREAD

**Issue by Gravity89** [egoroof/yandex-music-fisher#39]
Хотелось бы в настройках плагина иметь возможность менять папку загрузки на произвольную. А то папка Chrome обычно та еще помойка, а так удобно было бы указывать куда сохраняется конкретно это дополнение.

P.S. Спасибо Вам большое за работу над этим проектом. Миру нужны такие люди ;)

**Comment by egoroof** [comment]
Спасибо за тёплые слова!

К сожалению, возможности расширений ограничены. Касаемо выбора папки загрузки - всё сохраняется в папку, указанную [в настройках браузера](https://support.google.com/chrome/answer/95574?hl=ru). Единственное, что может расширение- создавать там подпапки.

**Comment by egoroof** [comment]
Вероятно, создание произвольной подпапки будет реализовано: https://github.com/egoroof/yandex-music-fisher/issues/60 (возможно не совсем то, что вы хотели)
