### ISSUE TITLE
Расширение нумерует треки в плейлисте даже когда галочка выключена

### ISSUE THREAD

**Issue by 4ndv** [egoroof/yandex-music-fisher#40]
![image](https://cloud.githubusercontent.com/assets/10115449/11580414/7ba6b810-9a61-11e5-983b-150a6b6fbbc4.png)
![image](https://cloud.githubusercontent.com/assets/10115449/11580417/844d4394-9a61-11e5-88f9-7bd5f024198b.png)
Сабж

**Comment by Gravity89** [comment]
Подтверждаю наличие проблемы. Сложность в том, что когда ты добавил 1 трек в плейлист себе и хочешь его перезакачать, то он перезакачает весь плейлист, но еще и под разными именами файлов.

**Comment by egoroof** [comment]
исправление будет в следующей версии
