### ISSUE TITLE
Возможность скачивания треков с radio.yandex

### ISSUE THREAD

**Issue by ravenich** [egoroof/yandex-music-fisher#47]
Можно ли добавить возможность скачивания треков с radio.yandex? Было бы очень удобно, сейчас приходится переходить по ссылке с песней.

**Comment by Gravity89** [comment]
Хм. Как вариант поставить [Яндекс.Музыка - управление плеером](https://chrome.google.com/webstore/detail/яндексмузыка-управление-п/gcfheefljlblchcfjlknidfimnfillec)
В нем настроить глобальные быстрые клавиши для добавления в Мне нравится. И потом уже, по мере необходимости, выкачивать этот плейлист пачкой. 
П.С. расширение все еще не знает какие файлы ты уже скачивал... =(

**Comment by egoroof** [comment]
@ravenich такая возможность есть в планах.

**Comment by dokxpi** [comment]
Gravity89, я тоже пользуюсь таким методом

**Comment by egoroof** [comment]
Будет в следующей версии
