### ISSUE TITLE
Некорректное отображение состояния загрузки альбома

### ISSUE THREAD

**Issue by oxaoo** [egoroof/yandex-music-fisher#48]
Обратите внимание на процент загрузки и объем загруженных данных.
![image](https://cloud.githubusercontent.com/assets/7817519/12183166/364ae55e-b59e-11e5-8f5a-0f5407651219.png)

**Comment by dokxpi** [comment]
oxaoo, https://github.com/egoroof/yandex-music-fisher/releases/tag/v1.3.0
Yandex Music Fisher (1.6.0)
![2016-01-08_032636](https://cloud.githubusercontent.com/assets/10334512/12187809/b056221e-b5b7-11e5-9087-669307c1c921.png)

**Comment by egoroof** [comment]
@oxaoo спасибо, что сообщили о проблеме. Её обсуждение тут: https://github.com/egoroof/yandex-music-fisher/issues/31
