### ISSUE TITLE
Не скачивается 320 кбит/сек

### ISSUE THREAD

**Issue by edikstepanov** [egoroof/yandex-music-fisher#50]
![default](https://cloud.githubusercontent.com/assets/16903895/12589958/8c7779e2-c471-11e5-90b2-eb8e11c516f2.png)

Не скачивается 320, в настройках приложения стоит галочка, версия 16.0, Хром 48.0.2564.82 m
Слева скачал через Network->Media, справа через Фишер. Даже подписку купил.

**Comment by egoroof** [comment]
Дайте ссылку на трек, пожалуйста

**Comment by egoroof** [comment]
А попробуйте сейчас ещё раз скачать через `Network->Media`. Я попробовал - у меня 192 качает. Может какой-нибудь кэш?

**Comment by Schokn-Itrch** [comment]
У меня 192 при любых вариантах настроек плагина и/или авторизации в яндексе.

**Comment by egoroof** [comment]
О, там теперь высокое качество только по подписке доступно:
![2016-01-27 13 31 26](https://cloud.githubusercontent.com/assets/2605831/12604864/691ad186-c4fa-11e5-95a2-98f3f959d022.png)

**Comment by egoroof** [comment]
@edikstepanov обновите расширение до `1.7.0` и проверьте, скачиваются ли треки в высоком качестве, когда вы авторизованы под учётной записью с подпиской (при этом должна быть включена галочка в настройках). У меня её нет :(

**Comment by Gravity89** [comment]
Грусть, печаль. Закрыли лавочку. Теперь довольствоваться 192кбс =\

**Comment by edikstepanov** [comment]
@egoroof обновил, скачиваются в 320 при условии, что я авторизирован. Но показывает размер трека с битректом 192, но скачивается 320. Спасибо.

**Comment by edikstepanov** [comment]
![default](https://cloud.githubusercontent.com/assets/16903895/12640745/a4cba210-c5bc-11e5-9427-1b70c68936f4.png)

**Comment by egoroof** [comment]
@edikstepanov по поводу неправильного размера трека в загрузчике - есть проблема, ага. Но её обсуждение тут: #31.

 А что на последнем скриншоте? Текущую проблему можно закрывать?

**Comment by edikstepanov** [comment]
@egoroof спасибо за помощь! Вы мне очень помогли! Вопрос решен.
