### ISSUE TITLE
v1.7.0 сломан  как минимум в Chromium 48.0.2564.82 Ubuntu 14.04 (64-bit)

### ISSUE THREAD

**Issue by RushOnline** [egoroof/yandex-music-fisher#51]
~~~
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

utils.js:50
yandex.js:9
storage.js:20
downloader.js:25
background.js:11
~~~

Не нравятся ему let? Забыт 'use strict' ? Откатился на v1.6.0 - он рабочий.

**Comment by RushOnline** [comment]
Прошу прощения, что не указал сразу - возможно в этом и кроются проблемы. Действительно, я загружаю расширение из локальной директории srс склонированного репозитория yandex-music-fisher, так как никаких стандартных методов сборки расширения не обнаружил. ЧЯДНТ?

**Comment by egoroof** [comment]
Как раз недавно перевёл на сборщик. В [readme ](https://github.com/egoroof/yandex-music-fisher) в самом низу написано, как собирать. Но если вы только пользоваться хотите, то рекомендую скачивать дистрибутив - там уже всё собрано, меньше мороки.

**Comment by RushOnline** [comment]
Ну я во-первых вдруг вас найдут киллеры Яндекса? :) Хочу на всякий случай иметь копию репозитория, поэтому локальный репозиторий у меня является клоном форка вашего репозитория, ваш репозиторий добавлен как upstream.  :) Во вторых при желании у меня будет либо возможность сделать pull request, либо свою ветку.

Про сборку - что то  я упустил момент, когда в репе появился package.json.

Инструкция для дистрибутивов, основанных на Debian (может и вам пригодится - для README):

~~~bash

sudo apt-get install nodejs-legacy npm
git clone https://github.com/egoroof/yandex-music-fisher.git
cd yandex-music-fisher
npm install && npm run build
...
# Загружаем распакованное расширение из src
~~~

**Comment by egoroof** [comment]
> вдруг вас найдут киллеры Яндекса? :) 

На такой случай на гитхабе уже 44 форка + зеркало на битбакете и один форк там. Нужно сразу много киллеров нанимать, а при текущей экономической ситуации дороговато выйдет :smile: 

> что то я упустил момент, когда в репе появился package.json

[23.01.16](https://github.com/egoroof/yandex-music-fisher/commit/c6aed2547ee86142e36bb4103a2844a4521867aa)

Спасибо за инструкцию, может быть сюда и зайдёт кто-нибудь очень бородатый, чтобы ей воспользоваться. Но в основном расширением пользуются обычные смертные, которые просто поставят дистрибутив :)

**Comment by RushOnline** [comment]
> Но в основном расширением пользуются обычные смертные, которые просто поставят дистрибутив

Ну да, 44 форка - это простые смертные :)

Спасибо за потраченное на глупый вопрос время, это всё из за моей невнимательности.

**Comment by egoroof** [comment]
> Ну да, 44 форка - это простые смертные

Ну тут же просто на гитхабе один клик мышкой - и ты сделал себе форк, даже если не слышал про гит :) Если не ошибаюсь, за всё время было суммарно 3 коммита от других людей (по 1 на каждого). Гугл говорит, что за последние 30 дней пользовались расширением 4412 пользователей. Вот такая статистика :)

> Спасибо 

Всегда пожалуйста :)

**Comment by dokxpi** [comment]
@RushOnline проще воспользоваться инструкцией текущего README

1. установить Node.js.
2. запустить сборку из батника
```
cd /d d:\Dropbox\GitHub\yandex-music-fisher\
npm install && npm run build
```

**Comment by RushOnline** [comment]
@dokxpi спасибо, но вопрос то решён четыре сообщения и месяц назад :) И вопрос собственно  был не про винду и не про хром :)

**Comment by dokxpi** [comment]
@egoroof 
> Node.js
> + 14 hidden modules
> Недостаточно памяти для обработки команды.

Игрался с батником и вот тебе вывалено, подскажите, с этим можно как то бороться?

**Comment by egoroof** [comment]
@dokxpi по-подробнее опишите ситуацию. Что в батнике написано. Какая версия nodejs?

**Comment by dokxpi** [comment]
@egoroof 
> Так может и правда недостаточно памяти?

 Ошибочно в планировщик не тот батник добавил, в общим раз 40 оно там запускалось и теперь вот ... - недостаточно памяти. 
Как её очистить, этот Node ведь куда то слаживает эти webpack`и? 
>Что выводит команда npm run build? (папку moduls из репозитория удалил )
[note.txt](https://github.com/egoroof/yandex-music-fisher/files/150817/note.txt)

**Comment by egoroof** [comment]
> После удаления из репозитория yandex-music-fisher, папки moduls, расширение по прежнему работает

Нужно обновить расширение, тогда, браузер должен заругаться на отсутствие манифеста

> Ошибочно в планировщик не тот батник добавил, в общим раз 40 оно там запускалось и теперь вот ... - недостаточно памяти. 

Зачем вообще что-то добавлять в планировщик? И зависимости нужно один раз установить (потом только обновлять при необходимости). А при изменении исходных кодов расширения для сборки нужно только вызвать команду `npm run build`.

>  этот Node ведь куда то слаживает эти webpack`и?

Все сгенерированные файлы находятся в папке с расширением > src > bundle.

**Comment by dokxpi** [comment]
Разобрался, спасибо 

> Зачем вообще что-то добавлять в планировщик?

Да я и не собирался, ошибочно

**Comment by egoroof** [comment]
Немного обновил инструкцию сборки (смотрите README.md) - убрал лишний шаг с установками зависимостей. Теперь очистка, обновление и установка зависимостей будут автоматически происходить при запуске `npm run build`.
