### ISSUE TITLE
Проблема с обложками

### ISSUE THREAD

**Issue by Schokn-Itrch** [egoroof/yandex-music-fisher#52]
Отсутствует обложка = циклическое скачивание = ошибка.
https://music.yandex.ru/album/99853/track/879704

**Comment by egoroof** [comment]
А какая у вас версия расширения?

**Comment by Schokn-Itrch** [comment]
1.7.0

**Comment by egoroof** [comment]
Проблема подтвердилась, причину выявил, ждите следующую версию.

**Comment by egoroof** [comment]
Доступно в версии `1.7.1`. Спасибо, что сообщили о проблеме!

**Comment by Schokn-Itrch** [comment]
Спасибо за оперативность, но всё осталось на месте. Может быть это поможет.
![tr_02](https://cloud.githubusercontent.com/assets/16912209/12696607/43baea56-c780-11e5-9a04-851277aab946.png)

**Comment by egoroof** [comment]
О, теперь обнаружил другую проблему :)

**Comment by egoroof** [comment]
Исправлено в версии `1.7.2`. Ещё раз спасибо, что сообщили о проблеме! :+1:

**Comment by Schokn-Itrch** [comment]
Спасибо, хоть не удовлетворительно, по моим меркам, но работает, а это главное :)

**Comment by egoroof** [comment]
> хоть не удовлетворительно

А можете более детально описать, что вас не удовлетворяет? Возможно в будущем что-то можно будет изменить.

> подставляет обложку, фиг знает откуда, но подставляет.

Что значит фиг знает откуда? Обложка берётся из альбома скачиваемого трека. Если где-то это не так - скиньте ссылку, пожалуйста.

**Comment by egoroof** [comment]
> Кстати подставляет обложку, фиг знает откуда, но подставляет.

Нашёл проблему, исправление будет в следующей версии. Никто почему-то раньше не сообщал об этом. Так что спасибо!
