### ISSUE TITLE
название трека?

### ISSUE THREAD

**Issue by aus75** [egoroof/yandex-music-fisher#53]
при скачивании любого трека, в названии файла видим что-то типа: 28bc24fc-1fba-43a1-be2b-8324c5673242.mp3 или bccc2c65-2c01-467a-8e7e-9cc00bc43f26.mp3 , но теги вроде прописываются. Нельзя сделать чтобы файлы при сохранении имели вид названия исполнителя и композиции? Спасибо.  Браузер CHROME.

**Comment by egoroof** [comment]
> файлы при сохранении имели вид названия исполнителя и композиции

Именно так и должно работать. Вероятно, какая-то ошибка. Видел такое в некоторых других браузерах.

Пожалуйста, укажите следующую информацию:

1. название и версию вашей операционной системы
2. версию хрома
3. одну ссылку на яндекс музыку, откуда вы качаете

**Comment by aus75** [comment]
��03.02.2016, 11:31, "Tema" <notifications@github.com>:����� ��� ���������� ����� ��� �������� ����������� � ���������������� ��� � ������ ��������. ��������, �����-�� ������. ����� ����� � ��������� ������ ���������.����������, ������� ��������� ����������:�������� � ������ ����� ������������ �������windows 10������ ����������� 48.0.2564.97 m���� ������ �� ������ ������, ������ �� �������https://music.yandex.ru/feed�������� ��� ������ ����, ���� ���������� ��� ������: e9c59244-d039-4f1d-a93a-da52fd1b3da3.mp3, � ������ ���� ����: Enya - And Winter Game.mp3�� ���������, �������.�

**Comment by egoroof** [comment]
> windows 10
> Версия 48.0.2564.97 m

У меня точно такая же конфигурация, к сожалению. 

А какая версия самого расширения?

**Comment by aus75** [comment]
само расширение 1.7.2

**Comment by egoroof** [comment]
Совсем в тупик зашёл :(

Предлагаю немного поспособствовать мне - скачайте это тестовое расширение: https://github.com/egoroof/sample-chrome-extension/archive/master.zip. Распакуйте и установите аналогично, как и yandex-music-fisher. После установки сразу должна скачаться картинка (2КБ). Напишите сюда, какое будет название у картинки.

**Comment by aus75** [comment]
скачалась картинка под таким именем: 2605831.png

**Comment by aus75** [comment]
может стоит компьютер перегрузить, а то я постоянно в спящий режим его отправляю, давно не перегружал.

**Comment by egoroof** [comment]
> может стоит компьютер перегрузить, а то я постоянно в спящий режим его отправляю, давно не перегружал.

Да, попробуйте.

> скачалась картинка под таким именем: 2605831.png

Отлично! Это немного сужает область проблемы. Как что-нибудь надумаю, напишу сюда. Спасибо за помощь.

**Comment by egoroof** [comment]
А вот ещё тест - сделайте тоже самое, что я выше описал, только теперь скачайте по этой ссылке: https://github.com/egoroof/sample-chrome-extension/archive/filename.zip

**Comment by aus75** [comment]
2605831.png  такое же имя файла, и перезагрузка ничего не дала. :(

**Comment by aus75** [comment]
ничего что я эти временные расширения удаляю из браузера после скачивания png файла?

**Comment by egoroof** [comment]
> ничего что я эти временные расширения удаляю из браузера после скачивания png файла?

Да, так и надо, это одноразовый тест.

> 2605831.png

Это плохо. Должно было измениться. Значит дело не в конкретном расширении, а в браузере. Может установленны какие-либо плагины? Проверить можно на странице по адресу chrome://plugins/

**Comment by egoroof** [comment]
А случаем вы флаги в хроме не меняли (которые на странице chrome://flags/)?

**Comment by aus75** [comment]
нет не менял. стоит плагин skyload который тоже вроде должен качать музыку с этого сайта, пробовал его временно отключить - не помогло, может совсем удалить?

**Comment by aus75** [comment]
он тоже имя файла кракозябрит

**Comment by egoroof** [comment]
> пробовал его временно отключить - не помогло

Не поможет, ага.

А скиньте скриншот со страницы chrome://version/

**Comment by aus75** [comment]
плагины стоят такие: 
Widevine Content Decryption Module 
Chrome PDF Viewer
Native Client
Adobe Flash Player

**Comment by aus75** [comment]
Google Chrome	48.0.2564.97 (Официальная сборка) m (32 бит)
Версия	97d2b858fc7c3d480a52f4b58ed72c76fa535598-refs/branch-heads/2564@{#631}
ОС	Windows 
Blink	537.36 (@97d2b858fc7c3d480a52f4b58ed72c76fa535598)
JavaScript	V8 4.8.271.17
Flash	20.0.0.286
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
Командная строка	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Путь к исполняемому файлу	C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Путь к профилю	C:\Users\Alexey\AppData\Local\Google\Chrome\User Data\Default
Варианты	47f591a-ce48e7a2
c175bf3c-4d5a0d36
6345b824-3d47f4f4
e950616e-ca7d8d80
7c1bc906-f55a7974
770a425-2aa41273
775ebbd7-ca7d8d80
c70841c8-a2567007
f15c1c09-ca7d8d80
fb124cc-803f8fc4
93731dca-3f4a17df
9e5c75f1-e1c7cd46
f5dd6118-3d47f4f4
f79cb77b-3d47f4f4
4ea303a6-3d47f4f4
4117e878-3d47f4f4
7aa46da5-669a04e0
9736de91-ca7d8d80
dbffab5d-ca7d8d80
c8b9b12d-f23d1dea
6844d8aa-669a04e0
f47ae82a-86f22ee5
3ac60855-486e2a9c
ed1d377-e1cc0f14
75f0f0a0-4ad60575
e7e71889-e1cc0f14
b39ea213-d1372334
bd368a6b-d2c8e0a4
Compiler	MSVC


так пойдет?

**Comment by aus75** [comment]
skyload вообще удалил - не помогло...

**Comment by egoroof** [comment]
> так пойдет?

Да.

Появилась идея! Скачайте хром 64битный: https://www.google.com/chrome/browser/desktop/index.html?platform=win64. Удалите установленный хром, затем установите скачанный 64битный и проверьте yandex-music-fisher.

**Comment by aus75** [comment]
теги кстати нормально прописывает, а вот имена файлов

**Comment by aus75** [comment]
а расширения установленные заново потом устанавливать все или можно их синхронизировать?

**Comment by egoroof** [comment]
честно не знаю. А вы в хроме вошли в свой аккаунт? Если да, то наверно будет синхронизироваться, но я не пробовал.

**Comment by aus75** [comment]
вообще через свой гугл, и там вроде всё должно. Сейчас попробую.

**Comment by egoroof** [comment]
https://habrahabr.ru/post/96793/ вроде ещё в 2010 появилась синхронизация расширений

**Comment by aus75** [comment]
ок. пробую 64 бита.

**Comment by aus75** [comment]
итак, переустановил 64 бита, итог тот же. Не сохраняет имя файла.

**Comment by aus75** [comment]
всё отбой. Победил таки. :)

**Comment by aus75** [comment]
расширение: менеджер загрузки chrono портило мне кровь, тратило ваше время и нервы. Отключил и всё заработало как надо. Спасибо. Теперь всё как я хотел.

**Comment by egoroof** [comment]
Дайте пожалуйста на него ссылку. Хочу выяснить, как он влияет на это.

Кроме того, в багтрекере хромиума нашёл такую же проблему: https://code.google.com/p/chromium/issues/detail?id=579563

**Comment by aus75** [comment]
https://chrome.google.com/webstore/detail/chrono-download-manager/mciiogijehkdemklbdcbfkefimifhecn?utm_source=chrome-app-launcher-info-dialog

**Comment by aus75** [comment]
если исправят, дайте знать пожалуйста - снова включу его...

**Comment by egoroof** [comment]
Спасибо за ссылку! Напишу, если что.

**Comment by egoroof** [comment]
Кстати, в браузере вивалди такая же проблема, но вызвана не конфликтом расширений: https://github.com/egoroof/yandex-music-fisher/issues/41.
