### ISSUE TITLE
Поддержка треков, добавленых из яндекс.диск

### ISSUE THREAD

**Issue by MikeGTi** [egoroof/yandex-music-fisher#54]
Скачал только 262 трека из 713 треков.
В плейлисте отобраны разные треки (yandex-овский плейлист "Мне нравиться")

**Comment by egoroof** [comment]
В процессе скачивания могут возникать различные ошибки. На такой случаи, расширение может докачать оставшиеся треки при нажатии на голубой квадратик:
![2016-02-03 12 35 52](https://cloud.githubusercontent.com/assets/2605831/12773127/727e3b86-ca73-11e5-9816-63e1f7369980.png)
Будут загружаться только оставшиеся треки (а не всё заново).

Если же после нажатия на голубой квадратик ничего нового не докачалось, возможно, нужно ввести капчу на любой странице яндекс музыки - просто откройте яндекс музыку и, если вы словили капчу, то вместо обычных страниц увидите поле для ввода капчи на всю страницу. После ввода, вас перекинет на обычные страницы. Затем можно снова возобновить скачивание через расширение.

Не помогло? Скиньте ссылку на плейлист, проверю.

**Comment by MikeGTi** [comment]
У меня не появляется голубой квадратик.
Cсылка на плейлист:
https://music.yandex.ru/users/mikegti/playlists/3

**Comment by egoroof** [comment]
> У меня не появляется голубой квадратик.

А что там написано (в загрузках)? "Загрузка" синего цвета и не меняющийся размер? Опишите подробности.

> https://music.yandex.ru/users/mikegti/playlists/3

Сделайте его публичным, а то я не вижу там треков.

**Comment by MikeGTi** [comment]
Добрый день! https://music.yandex.ru/users/mikegti/playlists/1005  С уважением, Бойчук Михаил.   03.02.2016, 09:21, "Tema" <notifications@github.com>:У меня не появляется голубой квадратик.А что там написано (в загрузках)? "Загрузка" синего цвета и не меняющийся размер? Опишите подробности.https://music.yandex.ru/users/mikegti/playlists/3Сделайте его публичным, а то я не вижу там треков.—Reply to this email directly or view it on GitHub.

**Comment by egoroof** [comment]
> походу натыкается на треки из яндекс диска и не может их загрузить

Да..
Раньше не сталкивался с этим. Там формат немного другой.

Спасибо, что сообщили о проблеме. Как будет время добавлю поддержку для яндекс.диска.

**Comment by MikeGTi** [comment]
Спасибо за тех. поддержку!

**Comment by egoroof** [comment]
Будет доступно в следующей версии.

**Comment by dokxpi** [comment]
> Спасибо, что сообщили о проблеме. Как будет время добавлю поддержку для яндекс.диска.

Не всё так гладко (1.8.1)
Треки добавленные из Яндекс.Диска доступны "только" на странице плейлиста, в остальных случаях фишер негодует 
![2](https://cloud.githubusercontent.com/assets/10334512/13434933/7d3241ee-dfe0-11e5-88da-254c14dddd02.png)

**Comment by egoroof** [comment]
> Треки добавленные из Яндекс.Диска доступны "только" на странице плейлиста, во всех остальных случаях - нет.

А какие есть "остальные случаи"?

> К сожалению, для треков, добавленных из Яндекс.Диска, подобные ссылки не работают.

Да, всё верно. Туда ведь можно совершенно любую информацию написать. Как яндекс.музыка сможет узнать ссылку?

**Comment by egoroof** [comment]
> ![](https://cloud.githubusercontent.com/assets/10334512/13434933/7d3241ee-dfe0-11e5-88da-254c14dddd02.png)

А на какой странице и при каких обстоятельствах вы получили такое окно?

**Comment by dokxpi** [comment]
> Да, всё верно. Туда ведь можно совершенно любую информацию написать. Как яндекс.музыка сможет узнать ссылку?

Добавлял официальные треки 
Им по барабану. Хоть бы включили на уровни аккаунта

**Comment by dokxpi** [comment]
> А на какой странице и при каких обстоятельствах вы получили такое окно?

Просто уберите возможность скачивания играющего трека, для треков добавленных из Яндекс.Диска и проблемы решаться

**Comment by egoroof** [comment]
> скачивания играющего трека, для треков добавленных из Яндекс.Диска

всё, понял, поправлю

**Comment by dokxpi** [comment]
Странно, теперь у меня в плейлистах треки добавленные из Я.Диск помечены как "трек не доступен" У всех так? Больше 200 
![2016-06-27_215707](https://cloud.githubusercontent.com/assets/10334512/16391953/29d46a48-3cb2-11e6-83e9-7c9ab5e17239.png)
