### ISSUE TITLE
отключение напоминания?

### ISSUE THREAD

**Issue by aus75** [egoroof/yandex-music-fisher#56]
Скажите, а можно ли как-нибудь в CHROME отключить напоминание при каждом запуске браузера об отключении расширения в режиме разработчика?

**Comment by egoroof** [comment]
Чтобы не использовать [муторные методы](https://www.google.ru/search?q=%D0%BE%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F+%D0%B2+%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B5+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B0) рекомендую отключить расширение и вы больше не увидите это напоминание. А при необходимости скачать музыку идём на страницу расширений и включаем его.
Кроме того, можно у расширения включить настройку "Работать в фоновом режиме" и при закрытии окон браузера хром полностью не будет отключен, поэтому, когда вновь откройте окна браузера, то не увидите это оповещение.

**Comment by egoroof** [comment]
Теперь можно. Установите расширение из [интернет-магазина Chrome](https://chrome.google.com/webstore/detail/yandex-music-fisher/gkdpmbjlfgjbnleinnojgpgoljaokbni).
