### ISSUE TITLE
Возможность изменить папку загрузок на свою

### ISSUE THREAD

**Issue by Necronru** [egoroof/yandex-music-fisher#60]
Было бы не плохо менять по умолчанию папку куда складываются треки. Не всегда удобно переносить треки после скачивания в папку Music к примеру.

**Comment by egoroof** [comment]
Можно путь строить только "вглубь" папки загрузок браузера (создавая подпапки). Правильно ли я понял, что подпапка произвольного имени - то, что требуется?
Пример: загрузки по-умолчанию сохраняются браузером в `E:\downloads`. В настройках расширения указывается папка `music`. Затем все загрузки расширением сохраняются в `E:\downloads\music`, так?

**Comment by Necronru** [comment]
Как вариант :)

**Comment by Necronru** [comment]
При скачивании "10 лучших треков" было бы хорошо складывать их в отдельные папки по названию исполнителя / альбома / etc. 
Или так-же дать возможность настраивать это пользователю.

Сегодня скачивал треки именно по 10 лучших по нескольким исполнителям. В итоге получил в папке Downloads кашу из 500 треков :) Так как музыку слушаю в машине - есть необходимость раскладывать по папкам все, вообщем раскладывал в ручную.

**Comment by dokxpi** [comment]
Голосую за   `исполнитель  / etc.` (для "10 лучших треков")

@Necronru 10 треков = 10 альбомов 😆

Альбомы лишние!

**Comment by Necronru** [comment]
@dokxpi Согласен, альбомы лишние. В сообщении имел в виду что нужно структурировать скачаное :)

**Comment by dokxpi** [comment]
Плиз
> Голосую за исполнитель / etc. (для "10 лучших треков")

**Comment by egoroof** [comment]
Будет в следующей версии

**Comment by dokxpi** [comment]
Спасибо @egoroof , мы вас любим!!!!
