### ISSUE TITLE
Маленький баг на странице /feed

### ISSUE THREAD

**Issue by Necronru** [egoroof/yandex-music-fisher#61]
![monosnap 2016-03-16 10-44-40](https://cloud.githubusercontent.com/assets/2232309/13805245/57c96452-eb64-11e5-8734-5366f30f4a69.jpg)

**Comment by Necronru** [comment]
Версию билдил из ветки master

**Comment by egoroof** [comment]
Нужно обновить расширение на странице с расширениями браузера. И делать так каждый раз при новом билде (исключениями являются страница настроек и попап - там страница грузится во время её открытия).

**Comment by Necronru** [comment]
Тьфу! Точно же :)
Сорян :)
