### ISSUE TITLE
Порядок композиций в альбоме

### ISSUE THREAD

**Issue by deliseev** [egoroof/yandex-music-fisher#62]
Некоторые плееры ожидают видеть фрейм id3 'TRCK' в виде `номер-композиции`/`число-композиций-в-альбоме` (написано [тут](http://id3.org/id3v2.3.0#TRCK)). То же самое относится и к фрейму 'TPOS'. Лечится патчем к downloader.js:
`writer.setFrame('TRCK', entity.trackPosition + '/' + entity.track.albums[0].trackCount);`
Хотя вероятно возможна регрессия.

**Comment by egoroof** [comment]
По спецификации (приведённой вами же) возможно два варианта: который сейчас используется и который вы описали. Поэтому оба должны корректно обрабатываться плеерами... Или в каких-то плеерах всё же есть проблемы из-за этого?
Согласен, что лучше использовать ваш вариант (более информативен). Но, к сожалению, ближайшее время не планируются новые релизы.

**Comment by deliseev** [comment]
На счёт спецификации согласен, а копать начал именно потому, что у меня в плеере была "каша".

**Comment by egoroof** [comment]
А что за плеер?

**Comment by deliseev** [comment]
Meizu Music (на Meizu mi2 mini). Но только что-то и с патчем всё равно засада. Именно скаченные YMF идут по алфавитному порядку названия композиции из id3. Конвертировал из flac (программой XLD на OS X) - идут по номерам треков. Сравнил фреймы id3 никаких существенных отличий не нашёл (TRCK в виде n/m). В общем буду копать дальше.

**Comment by egoroof** [comment]
Будет в следующей версии
