### ISSUE TITLE
Скачивать сразу весь текущий список воспроизведения

### ISSUE THREAD

**Issue by Barefooter** [egoroof/yandex-music-fisher#64]
Недавно я хотел обновить музыку в машине и мне нужно было скачать все песни из раздела Моя музыка. Их там 90 штук. Пришлось включать каждую на секунду, нажимать кнопку плагина... Еще и следить, чтобы не больше 4 потоков было. Хотелось бы нажать кнопку и получить на диске папку со всей музыкой из текущего списка на странице. Странно, что этой возможности нет.

**Comment by egoroof** [comment]
> из раздела Моя музыка

Это ведь плейлист? Скиньте адрес. Плейлисты обычно скачиваются в один клик

**Comment by Barefooter** [comment]
https://music.yandex.ru/users/stas-home/playlists
Здесь есть раздел Мне нравится.

**Comment by egoroof** [comment]
Нужно перейти непосредственно к плейлисту, нажав на его название в данном случае "Мне нравится". Тогда адрес станет таким: https://music.yandex.ru/users/stas-home/playlists/3 и иконка станет зелёного цвета. Тогда и скачаете в один клик весь плейлист.

**Comment by Barefooter** [comment]
Спасибо, разобрался. Все работает.
