### ISSUE TITLE
Больше чем 10 лучших

### ISSUE THREAD

**Issue by vnikolaenko** [egoroof/yandex-music-fisher#67]
Предлагаю сделать возможность выбора количества лучших треков для скачивания

**Comment by vnikolaenko** [comment]
Вот [мой pull request](https://github.com/egoroof/yandex-music-fisher/pull/68)

**Comment by britanik** [comment]
+1 ... наиболее частый кейс для меня

**Comment by Barefooter** [comment]
+1

**Comment by egoroof** [comment]
Будет в следующей версии
