### ISSUE TITLE
Поддержка zvooq.ru

### ISSUE THREAD

**Issue by muzzzic** [egoroof/yandex-music-fisher#69]
Здравствуйте.
Можно ли добавить скачивание с сайта zvooq.ru?

**Comment by egoroof** [comment]
Здравствуйте.

> Можно ли добавить скачивание с сайта zvooq.ru?

Технически можно, да. Но это явно выходит за рамки данного расширения, которое ориентированно на Яндекс.Музыку. Радио сюда добавилось из-за их общего источника музыки и программного интерфейса.
