### ISSUE TITLE
Не устанавливается на хром 50 версии

### ISSUE THREAD

**Issue by ilyarudziak** [egoroof/yandex-music-fisher#70]
Не удалось загрузить фоновый скрипт bundle/background.bundle.js.
Сразу на манифест ругалось что в корне не лежит. Переместил в корень и все равно ругается

**Comment by dokxpi** [comment]
А как вы его ставили? Дистрибутивом или из исходных кодов?

**Comment by ilyarudziak** [comment]
распаковал в папку и перетащил в хром

**Comment by egoroof** [comment]
@ilyarudziak А архив откуда брали, который распаковывали?

**Comment by ilyarudziak** [comment]
@egoroof https://github.com/egoroof/yandex-music-fisher/releases/download/v1.9.2/yandex-music-fisher_1.9.2.zip
я на днях на другом компе попробую может в винде проблема

**Comment by egoroof** [comment]
@ilyarudziak скорее всего неправильно распаковали архив, либо выбрали не ту папку в хроме. Попробуйте заново:
1. распаковываем, и получаем папку yandex-music-fisher, зайдя в которую вы увидите 5 папок и 1 файл - manifest.json.
2. в хроме выбираем именно ту папку, которую получили в пункте 1.

**Comment by ilyarudziak** [comment]
@egoroof ok. можете закрывать вопрос

**Comment by egoroof** [comment]
@ilyarudziak если всё-таки не получится - пишите.
