### ISSUE TITLE
проблема со скачиванием в режиме инкогнито

### ISSUE THREAD

**Issue by PetyaVodolaz** [egoroof/yandex-music-fisher#71]
Выбираю трек, жму на иконку ![GitHub Logo] (https://raw.githubusercontent.com/egoroof/yandex-music-fisher/master/readme_img/blue.png) , нажимаю скачать
начинается загрузка 
![123](https://cloud.githubusercontent.com/assets/19291086/15156046/5487da86-16f6-11e6-98f1-1d7a30a8d004.PNG) 
просит выбрать папку куда сохранять, выбираю. Ничего не скачивается.
Потом снова просит выбрать папку для сохранения этого же трека и так покругу.

**Comment by dokxpi** [comment]
Скачал этот же трек, и ничего, всё так, как должно быть
`Chrome. 50.0.2661.94 m (64-bit)`

**Comment by egoroof** [comment]
@PetyaVodolaz скиньте ссылку на трек, который вы пытаетесь скачать

**Comment by PetyaVodolaz** [comment]
https://music.yandex.ru/album/56602/track/527820

Но такая проблема не только с одним треком. Качаться вообще ничего не хочет: ни треки, ни плейлисты, ни альбомы.

**Comment by egoroof** [comment]
@PetyaVodolaz тогда проведите диагностику, как на гифке и сбросьте сюда ошибку:
![finderror](https://cloud.githubusercontent.com/assets/2605831/15200950/4429ce50-181e-11e6-807a-aca60cdfb0aa.gif)

**Comment by PetyaVodolaz** [comment]
`SERVER_BAD_CONTENT  background.bundle.js:205` 

Гифка с происходящим:
![gif123](https://cloud.githubusercontent.com/assets/19291086/15257916/c4d02b62-1959-11e6-9a36-65facfcc3759.gif)

**Comment by egoroof** [comment]
@PetyaVodolaz укажите название и версию вашего браузера. Судя по гифке у вас какой-то устаревший хром. Обновите браузер до последней версии и попробуйте скачать снова.
Да и теперь лучше ставьте расширение отсюда: https://chrome.google.com/webstore/detail/yandex-music-fisher/gkdpmbjlfgjbnleinnojgpgoljaokbni

**Comment by dokxpi** [comment]
@PetyaVodolaz  если вы самостоятельно собирали расширение, то возможно вы позабыли обновить build, смотрите [инструкцию по сборке](https://github.com/egoroof/yandex-music-fisher#Сборка-расширения-для-разработчиков) или просто поставьте расширение из Play Маркета https://chrome.google.com/webstore/detail/yandex-music-fisher/gkdpmbjlfgjbnleinnojgpgoljaokbni

PS. на гифке v1.1.0 .)

**Comment by PetyaVodolaz** [comment]
Переустановка из Гуглхром магазина решила все проблемы.
Благодарствую за помощь.

**Comment by egoroof** [comment]
Chromium 49.0.2623.108
![img](http://i.imgur.com/KbuoNaR.png?1)

**Comment by egoroof** [comment]
Причиной оказалось скачивание в режиме инкогнито.

**Comment by egoroof** [comment]
исправлено в 2.0.2
