### ISSUE TITLE
поддержка Firefox

### ISSUE THREAD

**Issue by egoroof** [egoroof/yandex-music-fisher#72]
Firefox активно пилят WebExtensions - это то, что позволит с минимальными изменениями запускать расширения хрома.
#### Проблемы:
- [x] [downloads.download не сохраняет blob](https://bugzilla.mozilla.org/show_bug.cgi?id=1271345) (49+)
- [x] [downloads.download не сохраняет в подпапки](https://bugzilla.mozilla.org/show_bug.cgi?id=1280044) (51+)
- [x] [всплывающее окно не меняет размер при изменении содержимого](https://bugzilla.mozilla.org/show_bug.cgi?id=1215025) (50+)

**Comment by egoroof** [comment]
Блокирующая проблема решена, спасибо @browserkit и @Barefooter, что поддержали в трекере файерфокса. Наконец-то удалось скачать трек с помощью 49й версии. Однако там ещё много мелких багов.

**Comment by ramzzzay** [comment]
О, великолепно. Тогда буду ждать версии в Firefox extension store. Так держать @egoroof , хороший у вас проект!

**Comment by egoroof** [comment]
> хороший у вас проект!

спасибо!

> Тогда буду ждать версии в Firefox extension store

долго придётся ждать :)

**Comment by Sc0rpi0n3** [comment]
Приветствую! Как дела с Firefox? Могу помочь в роли тестера, я заинтересован!

**Comment by pojuella** [comment]
Невозможно установить в Фирефокс 49
xpinstall.signatures.required --> false
не помогает

**Comment by egoroof** [comment]
На данный момент расширение ожидает проверки. Тестовая версия доступна тут: https://addons.mozilla.org/ru/firefox/addon/yandex_music_fisher/, однако в дальнейшем URL может измениться. Работает с Firefox 51+.

**Comment by egoroof** [comment]
URL в магазине Firefox изменился. В дальнейшем изменений не будет. Расширение по-прежнему стоит в очереди на проверку.

**Comment by Sc0rpi0n3** [comment]
@egoroof, а когда будет обновление Firefox до 51-ой версии? А то я поставил бету 51.0b6, в about:config сделал false на xpinstall.signatures.required  и все равно не ставится дополнение по ссылке. Может теперь новое поставится

**Comment by egoroof** [comment]
@Sc0rpi0n3 не ставится из-за того, что расширение ещё не проверили и не подписали в магазине. Как проверят, я тут напишу.

> about:config сделал false на xpinstall.signatures.required

Это сработает только в версиях dev-edition и nigthly, но не в стабильной и бете.

> а когда будет обновление Firefox до 51-ой версии?

24.01.17

**Comment by Sc0rpi0n3** [comment]
> только в версиях dev-edition и nigthly, но не в стабильной и бете
А, понял теперь, я так и думал, что надо develop версию. Спасибо!

**Comment by egoroof** [comment]
Проверяют невероятно медленно (там отображается позиция в очереди), такими темпами расширение будет проверено в 2017 году.. 😢

**Comment by Sc0rpi0n3** [comment]
А я-то думал у Firefox отличная техподдержка

**Comment by pojuella** [comment]
@Sc0rpi0n3
В НОЧНЫХ сборках -- работает
У меня -- 53.0a1 (2016-11-25) (32-бит)

**Comment by egoroof** [comment]
ууу, наконец-то ответили модераторы - запросили исходный код, сказав что ссылка на гитхаб не принимается..
Видать добрались до фишера, скоро наверно уже проверят.

**Comment by egoroof** [comment]
оооо, почти сразу заапрувили :) ура

**Comment by Sc0rpi0n3** [comment]
Отлично!
