### ISSUE TITLE
Не поддерживает ":" и "\" в имени пути загрузки

### ISSUE THREAD

**Issue by muzzzic** [egoroof/yandex-music-fisher#73]
Если указать Помещать загрузку в папку `D:\Download\MP3`, то скачивать будет в `D__Download_MP3` в папке загрузки по умолчанию.

Opera 37.0.2178.43
Yandex Music Fisher 2.0.2

**Comment by egoroof** [comment]
Папку загрузок браузера нельзя переопределить через расширение. Можно лишь создавать вложенные папки.
Поэтому рекомендую сделать так: у браузера установить загрузки в папку `D:\Download`, в фишере указать папку `MP3`. Тогда музыка, скаченная фишером будет в папке `D:\Download\MP3`.
