### ISSUE TITLE
Возможность скачивания "Моих треков"

### ISSUE THREAD

**Issue by gubenkoved** [egoroof/yandex-music-fisher#74]
Очень хотелось бы расширить функциональность плагани возможностью скачать "Понравившиеся песни" в один клик. На данный чтобы скачать список понравившихся песен нужно изрядно потрудиться, кликая по каждой и загружая их по одной.

> https://music.yandex.ru/users/user-id/tracks

![1](https://cloud.githubusercontent.com/assets/1703169/15769432/b9bc3b02-2963-11e6-9251-e63516c4e88a.png)

**Comment by Barefooter** [comment]
Откройте ссылку в отдельной странице, чтобы она была вида: https://music.yandex.ru/users/stas-home/playlists/3 Все прекрасно скачивается.

**Comment by gubenkoved** [comment]
Прекрасно, спасибо!
