### ISSUE TITLE
Неправильная реакция

### ISSUE THREAD

**Issue by Schokn-Itrch** [egoroof/yandex-music-fisher#76]
При нажатии на значок сразу начинается скачивание, вместо простого показа окна запроса. Из-за этого периодически приходится ждать чтобы не потерять ранее закачанные файлы.

**Comment by egoroof** [comment]
Честно говоря я не понял о чём речь. Пожалуйста опишите подробнее ваши действия и что вы ожидаете увидеть в результате. Может отключение настройки "Скачивать в одно нажатие" как-то поможет (если она включена)?
