### ISSUE TITLE
передача данных во внешнее API

### ISSUE THREAD

**Issue by wormen** [egoroof/yandex-music-fisher#79]
Собственно, то что интересует, в заголовке
если суть не ясна, то ... выглядит это так

например, я не хочу сохранять на свой комп скачанную музыку, а хочу к себе на сервер сразу закидывать, для этого

есть  свое API, я в него из вашего плагина отправляю полученные данные, а дальше сервис сам разгребает эти данные, сохраняет их в БД. если надо. скачивает файлы

меня собственно интересует, именно передача данных
планируется ли такое реализовать в плагине?

**Comment by PatSpiegel** [comment]
ты предлагаешь интегрировать в плагин ~FTP ? Или ты хочеш чтобы ссылка на скачивание mp3 файла которая генерируется под ip, передавалась на сервак которая бы скачивал. Это будет работать если ты сделаеш свой ип = сервак ип. Но опять таки, не легче сделать свой парсер мп3 файлов в твоём скрипте?

**Comment by wormen** [comment]
> ты предлагаешь интегрировать в плагин ~FTP ?

нет, я предлагаю сделать возможность передавать JSON, в REST(например сюда site.com/api/getDataMusic(POST), URL задается вручную), а далее владелец этого REST`а сам уже будет делать что хочет

> Но опять таки, не легче сделать свой парсер мп3 файлов в твоём скрипте?

и, лично я, как-то не заметил там привязку по IP. вот пример ссылки
https://s96e.storage.yandex.net/get-mp3/e7511d64578a750f5c0ea2d817f71bcd/00053ba3c9e6eaea/music/18/3/data-0.2:35471251810:7708838?track-id=24315194&play=false

как бы я не менял свой IP, все прекрасно открывается, даже без кук
