### ISSUE TITLE
Перестал работать во всех браузерах

### ISSUE THREAD

**Issue by pojuella** [egoroof/yandex-music-fisher#81]
31.10.2016
перестал работать
Все идет, как обычно, но загрузка не начинается

**Comment by MykolaKol** [comment]
Плюс 1. 
Есть ли инфа - будет пофикшено или нет, если главный дев в армии?

**Comment by ldavl** [comment]
Жизнь потеряла смысл. Почините. Спасибо.

**Comment by Bronxm** [comment]
egoroof - в армии. доступов нет. возможности писать код нет. прошу прощения за затишье

**Comment by Bronxm** [comment]
так что ломка по сервису затягивается на неопределенный срок (

**Comment by egoroof-army** [comment]
Надеюсь, что через месяц буду дома, а до тех пор, увы, ничего не смогу сделать.

**Comment by xandeadx** [comment]
Вот неплохая альтернатива - http://skyload.io/
Есть расширение для оперы и хрома

**Comment by pojuella** [comment]
Дело не в альтернативе ...
Есть и НетВидеоХантер
Теги-обложки теперь только вручную ... да и чохом не скачать ...

**Comment by Wells91** [comment]
ого уже через месяц надеюсь снова все заработает) думал год ждать будем пока придешь :)

**Comment by Bronxm** [comment]
месяц можно и подождать.

**Comment by muzzzic** [comment]
Эх, жаль я ни разу не программист! А то бы подпилил напильником.

**Comment by MihailovAlexander** [comment]
Да, престало работать. Очень ждем. Спасибо.

**Comment by kaener** [comment]
Привет.

Если кому интересно, вроде пофиксил (быстро подставил костыли чтоб работало) в своем форке, [качать тут](https://github.com/kaener/yandex-music-fisher/releases/tag/v2.0.4-alpha). По понятным причинам в интернет-магазинах обновить не могу, но, господа не-программисты, раз уж разобрались с гитхабом, разберётесь и с ручной установкой. :)

**Comment by Wells91** [comment]
@kaener опиши как установить) нуб прост)

**Comment by hyglok** [comment]
@kaener "version": "2.0.4-alpha". Тут "-alpha" надо убрать, по крайней мере у меня только так установился.

**Comment by kaener** [comment]
@Wells91 
В интернете легко гуглятся инструкции. Например, вот [три лёгких шага](http://pclion.ru/kak-ustanovit-extensions-google-chrome#Установка расширения не из магазина).

@hyglok 
Хм. Странно. Но сделал [v102.0.4](https://github.com/kaener/yandex-music-fisher/releases/tag/v102.0.4).
Но оно у тебя работает после установки? Я проверял только загрузку одного трека.

**Comment by hyglok** [comment]
@kaener 
Работает. Мне chrome писал, что version должен иметь только значения integer разделенные точкой.

**Comment by kaener** [comment]
@hyglok 
А, не знал о таком ограничении. Спасибо за тест.

**Comment by earendelby** [comment]
Спасибо. Но не знаю с чем связано - до изменения API с подпиской качал фишером файлы в качестве 320 kbps, сейчас те же файлы качаются с активной подпиской в 192. в чём подвох не понял.

**Comment by Wells91** [comment]
вот именно что с альфа не работал вчера а я сидел голову ломал, щас все работает спасибо)

**Comment by kaener** [comment]
@earendelby 
Тут, скорее всего, подвох в том же — новая версия API у Я.Музыки работает чуть иначе. Но у меня нет подписки, чтобы попробовать разобраться, так что c этим тебе придётся ждать уже оф. версию от @egoroof.

**Comment by Bronxm** [comment]
@kaener спасибо за фикс-апдейт работает.
надо мне тоже как-то добраться до изучения скриптов этих плагинов...)

**Comment by ldavl** [comment]
Остался 21 день

**Comment by highfeed** [comment]
Сколько там дней осталось? Ало!

**Comment by Barefooter** [comment]
Я тоже жду

19 Ноя 2016 г. 14:37 пользователь "Oleg Oskolsky" <notifications@github.com>
написал:

**Comment by kaener** [comment]
@Bronxm 
Пожалуйста.

@highfeed, @Barefooter 
Перестаньте спамить, пожалуйста. Все, кто подписан на этот ишью, ждут.
@egoroof писал 2 ноября _«Надеюсь, что через месяц буду дома…»_, значит до 2 декабря, т.е. 2 недели как минимум.

**Comment by pojuella** [comment]
1. В Хроме работает ! Спасибо !
2. Невозможно установить в Фирефокс 49.    xpinstall.signatures.required --> false  не помогает

**Comment by Gluk41** [comment]
> Вот неплохая альтернатива - ....
> Есть расширение для оперы и хрома
Чувак сверху эту дрянь посоветовал - не ведитесь!
Расширение само по-себе неплохое, но оно тащит в себе адварь, которая в наглую переадресовывает с нормальных страниц на рекламные сайты (пример: любая страница aliexpress преадресовывается на главную руверсии) и вполне может воровать данные.
Не ставьте это!

**Comment by muzzzic** [comment]
@Gluk41 если это так, напишите об этом хотя бы [тут](https://addons.opera.com/ru/extensions/details/skyload/).

**Comment by Gluk41** [comment]
@muzzzic Это так, и там вся страница исписана точно такими же комментами. 
Смотрите все комменты с рейтингом ниже двух звёзд. Все комменты с рейтингом 5 - заказные, это видно. Зайдите, посмотрите, сами всё поймёте.
Я даже в Яндекс успел наябедничать, правда тогда я не знал - что за расширение такие дела вытворяет. Это уже Яндекс мне помог, подсказали.

**Comment by egoroof** [comment]
Залил в магазины. У кого есть подписка яндекса, отпишитесь - качает ли в 320 кбит/с или только 192?

**Comment by muzzzic** [comment]
@egoroof в Opera до сих пор 2.0.3. Сколько времени обычно нужно подождать?

**Comment by egoroof** [comment]
@muzzzic в магазине оперы расширения проверяют люди, поэтому это зависит от проверяющих. Могут за день проверить, могут неделями молчать.

**Comment by egoroof** [comment]
@Man-Bot спасибо за информацию!

**Comment by egoroof** [comment]
@muzzzic в опере обновили до 2.0.4

**Comment by cjpavel** [comment]
У меня chrome, и подписка яндекса, качает странно, что то в 320, что то в 192, не понятно почему. при скачке у всех указывает два размера, т.е как понимаю при 320 и при 192к. версию поставил с магазина 2.04., до этого была 10204

**Comment by egoroof** [comment]
@cjpavel качает в наивысшем доступном качестве. Дело в том, что не все треки на яндекс.музыке есть с битрейтом 320кбит/с.

> при скачке у всех указывает два размера, т.е как понимаю при 320 и при 192

Верно, указывается диапазон. Подробнее тут: #31.

> Теперь размер загрузок будет отображаться в виде диапазона: A - B, где A - размер, при котором все треки с битрейтом 192 кбит/с, B - размер, при котором все треки с битрейтом 320 кбит/с. Поскольку в альбомах и плейлистах треки могут быть с различным битрейтом (от 192 до 320), то общий размер треков будет находиться в этом диапазоне.

**Comment by pojuella** [comment]
@ Gluk41 
Цитата: "Чувак сверху эту дрянь посоветовал - не ведитесь!
Расширение само по-себе неплохое, но оно тащит в себе адварь, которая в наглую переадресовывает с нормальных страниц на рекламные сайты (пример: любая страница aliexpress преадресовывается на главную руверсии) и вполне может воровать данные.
Не ставьте это!"

Согласен . Я писал ВКонтакте :
Никита,
Пытался поставить кучу 5* версий —то точки доступа нету, то ОС не та
Дело идет к тому, что для новой версии Ская нужно будет ОС апгрейдировать ..
.Не слишком ли для АПГРЕЙТА примочки ?
Где можно скачать ?
) - Хром 5*, чтоб работал в Вин ХР 32-бит 
) — старую версию Ская ?

**Comment by pojuella** [comment]
В Фирефркс для преодоления блокировки установки
пришлось установить  Firefox Nightly 53
Всё работает 
Спасибо !

**Comment by muzzzic** [comment]
@cjpavel вы можете дать ссылку на этот странный альбом?
FYI https://roem.ru/02-02-2016/218250/music-yandex-hifi/

**Comment by egoroof** [comment]
@pojuella firefox скоро тоже перестанет поддерживать win xp и vista: https://twitter.com/manentio/status/812055425117847552
