### ISSUE TITLE
Кнопка загрузки на самом треке и в альбомах

### ISSUE THREAD

**Issue by BANOnotIT** [egoroof/yandex-music-fisher#82]
Если честно, не очень удобно каждый раз переходить на страницу аудиозаписи, тыкать в расширение и там тыкать на "скачать". Было бы легче, если бы к самой аудиозаписи добавилась кнопка на скачивание именно этой аудиозаписи. На страницах альбомов тоже можно было бы сделать кнопку на скачивание именно этого альбома.

Как не крути, это только пожелание, с кодом помочь, к сожалению, времени нету. Но если у автора будет желание это сделать, то я буду ему очень благодарен.

PS
Очень благодарен, что кто-то вообще сделал это дополнение, оно очень удобное и очень помогающее (было, пока не перестало работать :D)
PSS
Ждём из армии.

**Comment by egoroof** [comment]
Дубликат #38.

> тыкать в расширение и там тыкать на "скачать"

Можно в настройках поставить "Скачивать в одно нажатие" и тогда будет на 1 действие меньше.

> Очень благодарен, что кто-то вообще сделал это дополнение, оно очень удобное и очень помогающее

Спасибо!
