### ISSUE TITLE
Если Я куплю подписку Яндекс музыки Я смогу скачивать в 320 kbps ?

### ISSUE THREAD

**Issue by Githubchenko** [egoroof/yandex-music-fisher#84]
Если да то будет ли у скачанных файлов отображаться что они 320 kbps ?

**Comment by dokxpi** [comment]
@Githubchenko [да!](https://github.com/egoroof/yandex-music-fisher/issues/31#issuecomment-202006860)

**Comment by egoroof** [comment]
Сможете, но не все треки есть в 320 https://roem.ru/02-02-2016/218250/music-yandex-hifi/
