### ISSUE TITLE
названия треков

### ISSUE THREAD

**Issue by IvvanVG** [egoroof/yandex-music-fisher#87]
Добрый день! Последнее время треки стали загружаться с подобным названием 1af7cce3-a20d-4009-bb63-87ae3e5b8472, а также не создается папка с названием плейлиста либо исполнителя, и скачанные треки не переносятся соответственно в указанную в настройках папку.
![2017-04-10](https://cloud.githubusercontent.com/assets/8935752/24858528/49bd1a7c-1e1f-11e7-8ebf-cd620f3a1e9b.png)
![2017-04-10 1](https://cloud.githubusercontent.com/assets/8935752/24858601/87a7503c-1e1f-11e7-9537-8d7cf00ad3ee.png)
![2017-04-10 2](https://cloud.githubusercontent.com/assets/8935752/24858639/b2097058-1e1f-11e7-8da1-daee67bad34f.png)

**Comment by egoroof** [comment]
Добрый день. Браузер - Вивальди?

**Comment by IvvanVG** [comment]
Chrome приложил скриншот

**Comment by egoroof** [comment]
Попробуйте отключить все другие расширения и проверьте проблему снова

**Comment by IvvanVG** [comment]
Помогло, сейчас выясню с чем конфликт

**Comment by IvvanVG** [comment]
конфликт с расширением Free Download Manager Chrome extension 2.1.42

**Comment by egoroof** [comment]
спасибо, вот похожая проблема (но там другое расширение) https://github.com/egoroof/yandex-music-fisher/issues/53
