### ISSUE TITLE
Не работает скачивание в папку на Vivaldi

### ISSUE THREAD

**Issue by Sheogorath2** [egoroof/yandex-music-fisher#88]
В настройках стоит папка *Music*, а скачивает прямо в загрузки. Кнопка *папка загрузок* также открывает загрузки.
Возможно, связано с #41, у меня этот баг также присутствует.

**Comment by egoroof** [comment]
Вы правильно указали на баг https://github.com/egoroof/yandex-music-fisher/issues/41 - папка ведь указывается с помощью названия файла, а поскольку оно игнорируется бразуром, то и папки нет
