### ISSUE TITLE
Скачиваются битые файлы

### ISSUE THREAD

**Issue by makkarpov** [egoroof/yandex-music-fisher#89]
https://mega.nz/#!24RCXSaL!Eq7XOqc_4aU7KHGA_4STaGaMi6l3N3UJYWa1bvrT9RE

Пример такого файла - удачная и одна из неудачных попыток скачивания.

Успех скачивания недетерменирован, один и тот же файл в разных итерациях как скачаться успешно, так и побиться (но из примерно 260 треков 200 скачиваются битыми). Появилось совсем недавно, день или два назад.

Бьются треки весьма капитально, во-первых, отличается размер (в меньшую сторону), во-вторых, команда `file` в UNIX-ОС определяет файл, как `AAC/ALAC+ID3`.

**Comment by egoroof** [comment]
Некоторые треки теперь в формате `aac` отдаются - возможно из-за этого проблемы.

**Comment by egoroof** [comment]
Если из "битых" треков удалить ID3 тег, то они будут воспроизводиться нормально (только не будет тега)

**Comment by egoroof** [comment]
Исправлено в версии `2.1.1`

**Comment by egoroof** [comment]
В хром сторе уже опубликована, в остальных проверка занимает больше времени

**Comment by egoroof** [comment]
Яндекс чо-то намудрили и один и тот же трек скачивается в разных кодеках и с разным битрейтом:

![screenshot 2017-05-05 22 50 50](https://cloud.githubusercontent.com/assets/2605831/25753408/919a66cc-31e5-11e7-9053-ac011edca45e.png)

**Comment by makkarpov** [comment]
![image](https://cloud.githubusercontent.com/assets/1329592/25753835/b14c6922-31c5-11e7-9e6b-a65965d75016.png)
Что-то пошло не так

**Comment by egoroof** [comment]
Вы в браузере случайно не включили опцию, запрашивающую куда сохранять каждый файл?

**Comment by makkarpov** [comment]
Да, действительно, что-то я как-то про неё забыл.

**Comment by egoroof** [comment]
Про это есть старый баг https://github.com/egoroof/yandex-music-fisher/issues/4

**Comment by makkarpov** [comment]
Как я понимаю, для m4a теги не пишутся чисто в силу того, что в npm нет пакетов для их записи (я, во всяком случае, не нашел)? Возможно ли в таком случае (с галочкой в настройках, по умолчанию отключенной) класть метаданные в отдельный файл, например, в JSON-формате (при этом для mp3 тоже)?

Позволит, как минимум, проставить эти метаданные внешними утилитами.

**Comment by egoroof** [comment]
> Как я понимаю, для m4a теги не пишутся чисто в силу того, что в npm нет пакетов для их записи

да

> Возможно ли в таком случае

возможно, но я не хочу зоопарк костылей городить) 

По-нормальному я вижу 2 решения: 

1. писать теги для m4a (у них формат отличается от ID3 тегов)
2. конвертировать трек в mp3 и добавлять ему обычный ID3 тег

**Comment by makkarpov** [comment]
... и в обоих случаях проще повеситься, чем реализовать это на JS, а стандартных пакетов нет.

А когда не получается по-нормальному, приходится вот так. Теоретически, еще можно конвертировать через внешний сервер, где можно сделать любую тяжелую логику, но это поднимает большие вопросы (например, где искать альтруистов/поднимать ли тем, кто хочет это использовать, свой приватный сервер).

**Comment by egoroof** [comment]
> Теоретически, еще можно конвертировать через внешний сервер

Такая же идея была с ID3 тегами https://github.com/egoroof/yandex-music-fisher/issues/9. Но потом я запил библиотеку для записи ID3 тегов на js :)

**Comment by makkarpov** [comment]
Тогда, наверное, стоит для этого запилить отдельный тикет, чтобы в этом не обсуждать.

**Comment by makkarpov** [comment]
Сейчас в отладчике порефрешил API-запрос для получения ссылки на файл (тот самый, у которого в ответе поле `codec`) - выпадает рандомно не только кодек, но и битрейт (у AAC он варьировался от 64 до 192). Во-первых, эти различия битрейта сами по себе стремные какие-то (но файлы я не сравнивал, м.б. звучание и не меняется), во-вторых, можно попробовать реализовать предпочтения вида "скачивать только в MP3" просто запрашивая API до тех пор, пока не выпадет нужный кодек (или пока не будет исчерпан лимит попыток).
