### ISSUE TITLE
Добавить ID3 теги в песни и настройки маски для именования файлов

### ISSUE THREAD

**Issue by alexivenin** [egoroof/yandex-music-fisher#9]
Очень не хватает ID3 тегов для песен и настройки маски для именования файлов.
Можно их добавить?

ps. А так - шикарный плагин. Большое спасибо.

**Comment by iCubeDm** [comment]
Ничего не прояснилось по поводу id3 тегов?

**Comment by gugglegum** [comment]
Пока нет, т.к. для этого нужен отдельный сервер, который бы эти ID3 теги добавлял в mp3.

**Comment by gugglegum** [comment]
Даже если такой сервер появится и расширение будет взаимодействовать с ним, в силу бесплатности публичного сервера не будет. Каждый пользователь будет вынужден поднимать такой сервер у себя локально или на каком-нибудь хостинге.

**Comment by dokxpi** [comment]
alexivenin, его тут же закроют, вы не первые

**Comment by egoroof** [comment]
ID3 тегам быть! :tada: Причём без всяких отдельных серверов, всё на JS!

**Comment by iCubeDm** [comment]
как?!)))) Неужели есть способ ковырять медийные файлы в области памяти браузера? Или API есть?

**Comment by egoroof** [comment]
@iCubeDm можно бинарные данные изменять на JS используя низкоуровневое API, такое как чтение и забись отдельных байтов (`ArrayBuffer` и `DataView`).
Есть даже библиотеки, которые преобразуют это дело в высокоуровневое API и можно уже оперировать объектами JS - строки, массивы и подобные структуры (https://github.com/jDataView/jBinary).

**Comment by iCubeDm** [comment]
Возможно ли узнать ориентировочную дату релиза этой фичи?

**Comment by egoroof** [comment]
По-быстрому не получится)
Рабочий код есть, но внедрить его в расширение в текущем виде не позволяют нюансы, например, способ загрузки треков - он другой, прогресс не отследить через загрузчик браузера, поэтому нужно сделать свой загрузчик с ~~блекждеком~~ отслеживанием прогресса. Кроме того юникод не поддерживается в id3 той версии, которую понимает windows, поэтому не все символы, которые есть в названиях треков, будут сохраняться.
Даты называть - тыкать пальцем в небо.

**Comment by alexivenin** [comment]
Отличная новость, будем ждать :)

**Comment by egoroof** [comment]
Ну вот, обновил расширение :+1:
