### ISSUE TITLE
Оригинальный MP3-файл каждого трека

### ISSUE THREAD

**Issue by kodzoyev** [egoroof/yandex-music-fisher#92]
Как и многие пользователи обратил внимание на то что сервис Яндекс Музыка начал буквально «подставлять» M4A-версии некоторых композиций вместо оригинальных доселе MP3-файлов. Однако, в исходном коде при проигрывании любого трека все также используется MP3-файл.

К примеру, альбом — https://music.yandex.ru/album/4334250

Трек **2. Arabian Heights** при загрузке альбома хранится в M4A-контейнере, однако при его воспроизведении сервис использует оригинальный MP3-файл (192 kbps) по адресу — 
https://s122e.storage.yandex.net/get-mp3/1d6e608dcb1450c070967caadca4d296/00054ed3e339bb88/music/28/5/data-0.12:29297251682:7387218?track-id=34574030&play=false

**UPD** Совсем запутался в странной избирательности сервиса, при обновлении страницы и очередной попытке вытянуть воспроизводимый файл из исходного кода браузера, сервис уже использует M4A-версию той же песни. То есть, когда как.

Есть предположение, что переход на новый контейнер связан с меньшим размером исходного файла, и как следствие, с более быстрой загрузкой оного. Однако, спрашивается, к чему эти грабли с мешаниной разных форматов. Может быть Яндекс тестирует таким образом этот переход?

И еще, как дела обстоят в платной версии, там тянет исключительно MP3-файлы (320 kbps)?

**Comment by egoroof** [comment]
> И еще, как дела обстоят в платной версии, там тянет исключительно MP3-файлы (320 kbps)?

Тянет то, что отдаёт Яндекс. Пользователи с платной подпиской подтверждали, что треки качаются в 320 (но не все https://roem.ru/02-02-2016/218250/music-yandex-hifi/).

**Comment by kodzoyev** [comment]
Кое-что прояснилось, но ответ расплывчатый. По утверждению их редакции, сервис выбирает версию с лучшим битрейтом (наверное тут скорее частота подразумевалась, битрейт у M4A обычно ниже). Что абсурдно, качество у M4A при правильной конвертации, всегда по частотам чуть выше чем у MP3, то есть следуя логике сервиса, вообще все треки должны загружаться в M4A, вместо этого, сервис именно КОГДА КАК загружает один и тот же трек то в M4A, то в MP3.
![-1](https://cloud.githubusercontent.com/assets/28471228/25770660/571f5c46-325d-11e7-8d02-f595e7c9f0a6.jpg)
