### ISSUE TITLE
Диалоговые окна Chrome при сохранении каждого файла

### ISSUE THREAD

**Issue by rinaldus** [egoroof/yandex-music-fisher#93]
Прежде всего, позвольте вас поблагодарить за чудесное приложение для скачивания Яндекс музыки.
Но у него есть один недостаток. Когда я выбираю закачку плейлиста, мой Chrome открывает столько же окон сохранения файла, сколько количество песен в плейлисте. Я вынужден постоянно тыкать в кнопку "Сохранить". На текущий момент у меня в плейлисте около 25 песен, а что будет, когда их будет 200? Эти окна подвесят мне комп, я полагаю. Вы не могли бы как-то модифицировать ваш аддон, чтобы этого избежать?

**Comment by egoroof** [comment]
Расширение не может переопределить эту настройку браузера - её нужно самому выключить. Но я как-то завёл тикет в багтрекера хрома https://bugs.chromium.org/p/chromium/issues/detail?id=417112 - висит с 2014 года.
Конкретно для этого расширения баг заведён здесь https://github.com/egoroof/yandex-music-fisher/issues/4.
