### ISSUE TITLE
Открывать папку загрузок в проводнике а не где попало

### ISSUE THREAD

**Issue by rumatoest** [egoroof/yandex-music-fisher#94]
Firefox на linux при нажатии на кнопку "папка загрузок" эта папка открывается в visual studio code
Как это возможно?
При чем если я в загрузках самого ФФ выбираю опцию открыть папку - открывается нормальный файловый менеджер (Dolphin в моем случае)

**Comment by egoroof** [comment]
Похоже на баг файерфокса

**Comment by rumatoest** [comment]
Возможно, но он сам из своего UI открывает папки в нужном проводнике.
Я надеюсь что у него АПИ одинаковое для этого действия.

А как мне проверить баг это или нет на своей стороне?

**Comment by egoroof** [comment]
> Я надеюсь что у него АПИ одинаковое для этого действия.

Да, там один метод без аргументов [browser.downloads.showDefaultFolder](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/showDefaultFolder)

> А как мне проверить баг это или нет на своей стороне?

Так ведь вы уже проверили. В крайнем случае может что-то не так с операционной системой.

Надо в багтрекер файерфокса писать.

**Comment by rumatoest** [comment]
После обновления списка приложений по умолчанию в kde проблема пропала. Возможно это какая комбинация багов firefox + kde.
