### ISSUE TITLE
Сделать пошире поле ввода с названием папки

### ISSUE THREAD

**Issue by rumatoest** [egoroof/yandex-music-fisher#95]
Хотелось бы иметь диалог на выбор папки куда помещать загрузки, а не поле ввода как сейчас.
Ну на крайний случай сделайте поле ввода шире

**Comment by egoroof** [comment]
Там есть ограничение, что можно создавать только подпапки в указанной в браузере папке. Выше уровнем не подняться. Глубже не имеет смысла. В итоге всё сводится к названию одной папки (а не её путь).
Пошире поле ввода сделать можно.
