### ISSUE TITLE
Опция для скачивание всех треков одним zip файлом

### ISSUE THREAD

**Issue by dima74** [egoroof/yandex-music-fisher#98]
Спасибо за Yandex Fisher!

Обычно пользуюсь им для скачивания всех песен исполнителя, которых может быть очень много (порядка ста). Соответственно неудобно много раз жать на кнопку сохранить файл. Будет круто, если добавите настройку, чтобы при скачивании песен из них сначала формировался zip файл, а затем один раз предлагалось этот файл скачать.

**Comment by egoroof** [comment]
Так ведь можно в настройках браузера отключить спрашивание, куда сохранять каждый файл

**Comment by dima74** [comment]
Да, действительно, не подумал об этом. Спасибо!
