### ISSUE TITLE
Проверять существует ли уже такой трэк в папке сохранения

### ISSUE THREAD

**Issue by OrangeFlag** [egoroof/yandex-music-fisher#99]
Было бы удобно не перекачивать весь плейлист заново, а докачивать лишь те треки, которые отсутствуют.
Спасибо за труд :+1:

**Comment by rootk1t** [comment]
Имхо, это будет сложно.

Сравнивал перекачанные заново треки, при повторном закачивании плейлиста. 

Многие треки имеют незначительно другой размер (обложка другого качества) + часто немного переделано имя трека, вследствии правок яндексом.

**Comment by OrangeFlag** [comment]
Это сложно будет сделать с текущими API  в принципе, они не дает проверять файлы в текущей директории(что правильно), я нашел только костыль в виде запроса пользователю, когда имена совпадают

**Comment by egoroof** [comment]
Дублирует https://github.com/egoroof/yandex-music-fisher/issues/28
